// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"
	"time"

	"golang.org/x/net/context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"
)

// NewDeleteDeploymentsNameParams creates a new DeleteDeploymentsNameParams object
// with the default values initialized.
func NewDeleteDeploymentsNameParams() *DeleteDeploymentsNameParams {
	var ()
	return &DeleteDeploymentsNameParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewDeleteDeploymentsNameParamsWithTimeout creates a new DeleteDeploymentsNameParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewDeleteDeploymentsNameParamsWithTimeout(timeout time.Duration) *DeleteDeploymentsNameParams {
	var ()
	return &DeleteDeploymentsNameParams{

		timeout: timeout,
	}
}

// NewDeleteDeploymentsNameParamsWithContext creates a new DeleteDeploymentsNameParams object
// with the default values initialized, and the ability to set a context for a request
func NewDeleteDeploymentsNameParamsWithContext(ctx context.Context) *DeleteDeploymentsNameParams {
	var ()
	return &DeleteDeploymentsNameParams{

		Context: ctx,
	}
}

// NewDeleteDeploymentsNameParamsWithHTTPClient creates a new DeleteDeploymentsNameParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewDeleteDeploymentsNameParamsWithHTTPClient(client *http.Client) *DeleteDeploymentsNameParams {
	var ()
	return &DeleteDeploymentsNameParams{
		HTTPClient: client,
	}
}

/*DeleteDeploymentsNameParams contains all the parameters to send to the API endpoint
for the delete deployments name operation typically these are written to a http.Request
*/
type DeleteDeploymentsNameParams struct {

	/*Name*/
	Name string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the delete deployments name params
func (o *DeleteDeploymentsNameParams) WithTimeout(timeout time.Duration) *DeleteDeploymentsNameParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the delete deployments name params
func (o *DeleteDeploymentsNameParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the delete deployments name params
func (o *DeleteDeploymentsNameParams) WithContext(ctx context.Context) *DeleteDeploymentsNameParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the delete deployments name params
func (o *DeleteDeploymentsNameParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the delete deployments name params
func (o *DeleteDeploymentsNameParams) WithHTTPClient(client *http.Client) *DeleteDeploymentsNameParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the delete deployments name params
func (o *DeleteDeploymentsNameParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithName adds the name to the delete deployments name params
func (o *DeleteDeploymentsNameParams) WithName(name string) *DeleteDeploymentsNameParams {
	o.SetName(name)
	return o
}

// SetName adds the name to the delete deployments name params
func (o *DeleteDeploymentsNameParams) SetName(name string) {
	o.Name = name
}

// WriteToRequest writes these params to a swagger request
func (o *DeleteDeploymentsNameParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param name
	if err := r.SetPathParam("name", o.Name); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
