// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"
	"time"

	"golang.org/x/net/context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"
)

// NewDeleteDynamicnodesIDParams creates a new DeleteDynamicnodesIDParams object
// with the default values initialized.
func NewDeleteDynamicnodesIDParams() *DeleteDynamicnodesIDParams {
	var ()
	return &DeleteDynamicnodesIDParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewDeleteDynamicnodesIDParamsWithTimeout creates a new DeleteDynamicnodesIDParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewDeleteDynamicnodesIDParamsWithTimeout(timeout time.Duration) *DeleteDynamicnodesIDParams {
	var ()
	return &DeleteDynamicnodesIDParams{

		timeout: timeout,
	}
}

// NewDeleteDynamicnodesIDParamsWithContext creates a new DeleteDynamicnodesIDParams object
// with the default values initialized, and the ability to set a context for a request
func NewDeleteDynamicnodesIDParamsWithContext(ctx context.Context) *DeleteDynamicnodesIDParams {
	var ()
	return &DeleteDynamicnodesIDParams{

		Context: ctx,
	}
}

// NewDeleteDynamicnodesIDParamsWithHTTPClient creates a new DeleteDynamicnodesIDParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewDeleteDynamicnodesIDParamsWithHTTPClient(client *http.Client) *DeleteDynamicnodesIDParams {
	var ()
	return &DeleteDynamicnodesIDParams{
		HTTPClient: client,
	}
}

/*DeleteDynamicnodesIDParams contains all the parameters to send to the API endpoint
for the delete dynamicnodes ID operation typically these are written to a http.Request
*/
type DeleteDynamicnodesIDParams struct {

	/*ID*/
	ID string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the delete dynamicnodes ID params
func (o *DeleteDynamicnodesIDParams) WithTimeout(timeout time.Duration) *DeleteDynamicnodesIDParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the delete dynamicnodes ID params
func (o *DeleteDynamicnodesIDParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the delete dynamicnodes ID params
func (o *DeleteDynamicnodesIDParams) WithContext(ctx context.Context) *DeleteDynamicnodesIDParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the delete dynamicnodes ID params
func (o *DeleteDynamicnodesIDParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the delete dynamicnodes ID params
func (o *DeleteDynamicnodesIDParams) WithHTTPClient(client *http.Client) *DeleteDynamicnodesIDParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the delete dynamicnodes ID params
func (o *DeleteDynamicnodesIDParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithID adds the id to the delete dynamicnodes ID params
func (o *DeleteDynamicnodesIDParams) WithID(id string) *DeleteDynamicnodesIDParams {
	o.SetID(id)
	return o
}

// SetID adds the id to the delete dynamicnodes ID params
func (o *DeleteDynamicnodesIDParams) SetID(id string) {
	o.ID = id
}

// WriteToRequest writes these params to a swagger request
func (o *DeleteDynamicnodesIDParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param id
	if err := r.SetPathParam("id", o.ID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
