// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	"github.com/fogatlas/client-go/models"
)

// DeleteDeploymentsNameReader is a Reader for the DeleteDeploymentsName structure.
type DeleteDeploymentsNameReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *DeleteDeploymentsNameReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 204:
		result := NewDeleteDeploymentsNameNoContent()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	case 400:
		result := NewDeleteDeploymentsNameBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	case 500:
		result := NewDeleteDeploymentsNameInternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewDeleteDeploymentsNameNoContent creates a DeleteDeploymentsNameNoContent with default headers values
func NewDeleteDeploymentsNameNoContent() *DeleteDeploymentsNameNoContent {
	return &DeleteDeploymentsNameNoContent{}
}

/*DeleteDeploymentsNameNoContent handles this case with default header values.

Deployment request deleted
*/
type DeleteDeploymentsNameNoContent struct {
}

func (o *DeleteDeploymentsNameNoContent) Error() string {
	return fmt.Sprintf("[DELETE /deployments/{name}][%d] deleteDeploymentsNameNoContent ", 204)
}

func (o *DeleteDeploymentsNameNoContent) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewDeleteDeploymentsNameBadRequest creates a DeleteDeploymentsNameBadRequest with default headers values
func NewDeleteDeploymentsNameBadRequest() *DeleteDeploymentsNameBadRequest {
	return &DeleteDeploymentsNameBadRequest{}
}

/*DeleteDeploymentsNameBadRequest handles this case with default header values.

Invalid request
*/
type DeleteDeploymentsNameBadRequest struct {
	Payload *models.Message
}

func (o *DeleteDeploymentsNameBadRequest) Error() string {
	return fmt.Sprintf("[DELETE /deployments/{name}][%d] deleteDeploymentsNameBadRequest  %+v", 400, o.Payload)
}

func (o *DeleteDeploymentsNameBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Message)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewDeleteDeploymentsNameInternalServerError creates a DeleteDeploymentsNameInternalServerError with default headers values
func NewDeleteDeploymentsNameInternalServerError() *DeleteDeploymentsNameInternalServerError {
	return &DeleteDeploymentsNameInternalServerError{}
}

/*DeleteDeploymentsNameInternalServerError handles this case with default header values.

Generic error
*/
type DeleteDeploymentsNameInternalServerError struct {
	Payload *models.Message
}

func (o *DeleteDeploymentsNameInternalServerError) Error() string {
	return fmt.Sprintf("[DELETE /deployments/{name}][%d] deleteDeploymentsNameInternalServerError  %+v", 500, o.Payload)
}

func (o *DeleteDeploymentsNameInternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Message)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
