// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	"github.com/fogatlas/client-go/models"
)

// DeleteApplicationsIDReader is a Reader for the DeleteApplicationsID structure.
type DeleteApplicationsIDReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *DeleteApplicationsIDReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 204:
		result := NewDeleteApplicationsIDNoContent()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	case 400:
		result := NewDeleteApplicationsIDBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	case 500:
		result := NewDeleteApplicationsIDInternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewDeleteApplicationsIDNoContent creates a DeleteApplicationsIDNoContent with default headers values
func NewDeleteApplicationsIDNoContent() *DeleteApplicationsIDNoContent {
	return &DeleteApplicationsIDNoContent{}
}

/*DeleteApplicationsIDNoContent handles this case with default header values.

application deleted
*/
type DeleteApplicationsIDNoContent struct {
}

func (o *DeleteApplicationsIDNoContent) Error() string {
	return fmt.Sprintf("[DELETE /applications/{id}][%d] deleteApplicationsIdNoContent ", 204)
}

func (o *DeleteApplicationsIDNoContent) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewDeleteApplicationsIDBadRequest creates a DeleteApplicationsIDBadRequest with default headers values
func NewDeleteApplicationsIDBadRequest() *DeleteApplicationsIDBadRequest {
	return &DeleteApplicationsIDBadRequest{}
}

/*DeleteApplicationsIDBadRequest handles this case with default header values.

Invalid request
*/
type DeleteApplicationsIDBadRequest struct {
	Payload *models.Message
}

func (o *DeleteApplicationsIDBadRequest) Error() string {
	return fmt.Sprintf("[DELETE /applications/{id}][%d] deleteApplicationsIdBadRequest  %+v", 400, o.Payload)
}

func (o *DeleteApplicationsIDBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Message)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewDeleteApplicationsIDInternalServerError creates a DeleteApplicationsIDInternalServerError with default headers values
func NewDeleteApplicationsIDInternalServerError() *DeleteApplicationsIDInternalServerError {
	return &DeleteApplicationsIDInternalServerError{}
}

/*DeleteApplicationsIDInternalServerError handles this case with default header values.

Generic error
*/
type DeleteApplicationsIDInternalServerError struct {
	Payload *models.Message
}

func (o *DeleteApplicationsIDInternalServerError) Error() string {
	return fmt.Sprintf("[DELETE /applications/{id}][%d] deleteApplicationsIdInternalServerError  %+v", 500, o.Payload)
}

func (o *DeleteApplicationsIDInternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Message)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
