// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	"github.com/fogatlas/client-go/models"
)

// DeleteRelationshipsIDReader is a Reader for the DeleteRelationshipsID structure.
type DeleteRelationshipsIDReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *DeleteRelationshipsIDReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 204:
		result := NewDeleteRelationshipsIDNoContent()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	case 400:
		result := NewDeleteRelationshipsIDBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	case 500:
		result := NewDeleteRelationshipsIDInternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewDeleteRelationshipsIDNoContent creates a DeleteRelationshipsIDNoContent with default headers values
func NewDeleteRelationshipsIDNoContent() *DeleteRelationshipsIDNoContent {
	return &DeleteRelationshipsIDNoContent{}
}

/*DeleteRelationshipsIDNoContent handles this case with default header values.

Relationship deleted
*/
type DeleteRelationshipsIDNoContent struct {
}

func (o *DeleteRelationshipsIDNoContent) Error() string {
	return fmt.Sprintf("[DELETE /relationships/{id}][%d] deleteRelationshipsIdNoContent ", 204)
}

func (o *DeleteRelationshipsIDNoContent) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewDeleteRelationshipsIDBadRequest creates a DeleteRelationshipsIDBadRequest with default headers values
func NewDeleteRelationshipsIDBadRequest() *DeleteRelationshipsIDBadRequest {
	return &DeleteRelationshipsIDBadRequest{}
}

/*DeleteRelationshipsIDBadRequest handles this case with default header values.

Invalid request
*/
type DeleteRelationshipsIDBadRequest struct {
	Payload *models.Message
}

func (o *DeleteRelationshipsIDBadRequest) Error() string {
	return fmt.Sprintf("[DELETE /relationships/{id}][%d] deleteRelationshipsIdBadRequest  %+v", 400, o.Payload)
}

func (o *DeleteRelationshipsIDBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Message)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewDeleteRelationshipsIDInternalServerError creates a DeleteRelationshipsIDInternalServerError with default headers values
func NewDeleteRelationshipsIDInternalServerError() *DeleteRelationshipsIDInternalServerError {
	return &DeleteRelationshipsIDInternalServerError{}
}

/*DeleteRelationshipsIDInternalServerError handles this case with default header values.

Generic error
*/
type DeleteRelationshipsIDInternalServerError struct {
	Payload *models.Message
}

func (o *DeleteRelationshipsIDInternalServerError) Error() string {
	return fmt.Sprintf("[DELETE /relationships/{id}][%d] deleteRelationshipsIdInternalServerError  %+v", 500, o.Payload)
}

func (o *DeleteRelationshipsIDInternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Message)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
