// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"
	"time"

	"golang.org/x/net/context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"
)

// NewDeleteMicroservicesIDParams creates a new DeleteMicroservicesIDParams object
// with the default values initialized.
func NewDeleteMicroservicesIDParams() *DeleteMicroservicesIDParams {
	var ()
	return &DeleteMicroservicesIDParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewDeleteMicroservicesIDParamsWithTimeout creates a new DeleteMicroservicesIDParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewDeleteMicroservicesIDParamsWithTimeout(timeout time.Duration) *DeleteMicroservicesIDParams {
	var ()
	return &DeleteMicroservicesIDParams{

		timeout: timeout,
	}
}

// NewDeleteMicroservicesIDParamsWithContext creates a new DeleteMicroservicesIDParams object
// with the default values initialized, and the ability to set a context for a request
func NewDeleteMicroservicesIDParamsWithContext(ctx context.Context) *DeleteMicroservicesIDParams {
	var ()
	return &DeleteMicroservicesIDParams{

		Context: ctx,
	}
}

// NewDeleteMicroservicesIDParamsWithHTTPClient creates a new DeleteMicroservicesIDParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewDeleteMicroservicesIDParamsWithHTTPClient(client *http.Client) *DeleteMicroservicesIDParams {
	var ()
	return &DeleteMicroservicesIDParams{
		HTTPClient: client,
	}
}

/*DeleteMicroservicesIDParams contains all the parameters to send to the API endpoint
for the delete microservices ID operation typically these are written to a http.Request
*/
type DeleteMicroservicesIDParams struct {

	/*ID*/
	ID string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the delete microservices ID params
func (o *DeleteMicroservicesIDParams) WithTimeout(timeout time.Duration) *DeleteMicroservicesIDParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the delete microservices ID params
func (o *DeleteMicroservicesIDParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the delete microservices ID params
func (o *DeleteMicroservicesIDParams) WithContext(ctx context.Context) *DeleteMicroservicesIDParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the delete microservices ID params
func (o *DeleteMicroservicesIDParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the delete microservices ID params
func (o *DeleteMicroservicesIDParams) WithHTTPClient(client *http.Client) *DeleteMicroservicesIDParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the delete microservices ID params
func (o *DeleteMicroservicesIDParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithID adds the id to the delete microservices ID params
func (o *DeleteMicroservicesIDParams) WithID(id string) *DeleteMicroservicesIDParams {
	o.SetID(id)
	return o
}

// SetID adds the id to the delete microservices ID params
func (o *DeleteMicroservicesIDParams) SetID(id string) {
	o.ID = id
}

// WriteToRequest writes these params to a swagger request
func (o *DeleteMicroservicesIDParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param id
	if err := r.SetPathParam("id", o.ID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
