// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	"github.com/fogatlas/client-go/models"
)

// DeleteThingsIDReader is a Reader for the DeleteThingsID structure.
type DeleteThingsIDReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *DeleteThingsIDReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 204:
		result := NewDeleteThingsIDNoContent()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	case 400:
		result := NewDeleteThingsIDBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	case 500:
		result := NewDeleteThingsIDInternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewDeleteThingsIDNoContent creates a DeleteThingsIDNoContent with default headers values
func NewDeleteThingsIDNoContent() *DeleteThingsIDNoContent {
	return &DeleteThingsIDNoContent{}
}

/*DeleteThingsIDNoContent handles this case with default header values.

thing deleted
*/
type DeleteThingsIDNoContent struct {
}

func (o *DeleteThingsIDNoContent) Error() string {
	return fmt.Sprintf("[DELETE /things/{id}][%d] deleteThingsIdNoContent ", 204)
}

func (o *DeleteThingsIDNoContent) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewDeleteThingsIDBadRequest creates a DeleteThingsIDBadRequest with default headers values
func NewDeleteThingsIDBadRequest() *DeleteThingsIDBadRequest {
	return &DeleteThingsIDBadRequest{}
}

/*DeleteThingsIDBadRequest handles this case with default header values.

Invalid request
*/
type DeleteThingsIDBadRequest struct {
	Payload *models.Message
}

func (o *DeleteThingsIDBadRequest) Error() string {
	return fmt.Sprintf("[DELETE /things/{id}][%d] deleteThingsIdBadRequest  %+v", 400, o.Payload)
}

func (o *DeleteThingsIDBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Message)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewDeleteThingsIDInternalServerError creates a DeleteThingsIDInternalServerError with default headers values
func NewDeleteThingsIDInternalServerError() *DeleteThingsIDInternalServerError {
	return &DeleteThingsIDInternalServerError{}
}

/*DeleteThingsIDInternalServerError handles this case with default header values.

Generic error
*/
type DeleteThingsIDInternalServerError struct {
	Payload *models.Message
}

func (o *DeleteThingsIDInternalServerError) Error() string {
	return fmt.Sprintf("[DELETE /things/{id}][%d] deleteThingsIdInternalServerError  %+v", 500, o.Payload)
}

func (o *DeleteThingsIDInternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Message)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
