// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	"github.com/fogatlas/client-go/models"
)

// DeleteNodesIDReader is a Reader for the DeleteNodesID structure.
type DeleteNodesIDReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *DeleteNodesIDReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 204:
		result := NewDeleteNodesIDNoContent()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	case 400:
		result := NewDeleteNodesIDBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	case 500:
		result := NewDeleteNodesIDInternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewDeleteNodesIDNoContent creates a DeleteNodesIDNoContent with default headers values
func NewDeleteNodesIDNoContent() *DeleteNodesIDNoContent {
	return &DeleteNodesIDNoContent{}
}

/*DeleteNodesIDNoContent handles this case with default header values.

node deleted
*/
type DeleteNodesIDNoContent struct {
}

func (o *DeleteNodesIDNoContent) Error() string {
	return fmt.Sprintf("[DELETE /nodes/{id}][%d] deleteNodesIdNoContent ", 204)
}

func (o *DeleteNodesIDNoContent) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewDeleteNodesIDBadRequest creates a DeleteNodesIDBadRequest with default headers values
func NewDeleteNodesIDBadRequest() *DeleteNodesIDBadRequest {
	return &DeleteNodesIDBadRequest{}
}

/*DeleteNodesIDBadRequest handles this case with default header values.

Invalid request
*/
type DeleteNodesIDBadRequest struct {
	Payload *models.Message
}

func (o *DeleteNodesIDBadRequest) Error() string {
	return fmt.Sprintf("[DELETE /nodes/{id}][%d] deleteNodesIdBadRequest  %+v", 400, o.Payload)
}

func (o *DeleteNodesIDBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Message)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewDeleteNodesIDInternalServerError creates a DeleteNodesIDInternalServerError with default headers values
func NewDeleteNodesIDInternalServerError() *DeleteNodesIDInternalServerError {
	return &DeleteNodesIDInternalServerError{}
}

/*DeleteNodesIDInternalServerError handles this case with default header values.

Generic error
*/
type DeleteNodesIDInternalServerError struct {
	Payload *models.Message
}

func (o *DeleteNodesIDInternalServerError) Error() string {
	return fmt.Sprintf("[DELETE /nodes/{id}][%d] deleteNodesIdInternalServerError  %+v", 500, o.Payload)
}

func (o *DeleteNodesIDInternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Message)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
