// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	"github.com/fogatlas/client-go/models"
)

// DeleteRegionsIDReader is a Reader for the DeleteRegionsID structure.
type DeleteRegionsIDReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *DeleteRegionsIDReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 204:
		result := NewDeleteRegionsIDNoContent()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	case 400:
		result := NewDeleteRegionsIDBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	case 500:
		result := NewDeleteRegionsIDInternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewDeleteRegionsIDNoContent creates a DeleteRegionsIDNoContent with default headers values
func NewDeleteRegionsIDNoContent() *DeleteRegionsIDNoContent {
	return &DeleteRegionsIDNoContent{}
}

/*DeleteRegionsIDNoContent handles this case with default header values.

region deleted
*/
type DeleteRegionsIDNoContent struct {
}

func (o *DeleteRegionsIDNoContent) Error() string {
	return fmt.Sprintf("[DELETE /regions/{id}][%d] deleteRegionsIdNoContent ", 204)
}

func (o *DeleteRegionsIDNoContent) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewDeleteRegionsIDBadRequest creates a DeleteRegionsIDBadRequest with default headers values
func NewDeleteRegionsIDBadRequest() *DeleteRegionsIDBadRequest {
	return &DeleteRegionsIDBadRequest{}
}

/*DeleteRegionsIDBadRequest handles this case with default header values.

Invalid request
*/
type DeleteRegionsIDBadRequest struct {
	Payload *models.Message
}

func (o *DeleteRegionsIDBadRequest) Error() string {
	return fmt.Sprintf("[DELETE /regions/{id}][%d] deleteRegionsIdBadRequest  %+v", 400, o.Payload)
}

func (o *DeleteRegionsIDBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Message)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewDeleteRegionsIDInternalServerError creates a DeleteRegionsIDInternalServerError with default headers values
func NewDeleteRegionsIDInternalServerError() *DeleteRegionsIDInternalServerError {
	return &DeleteRegionsIDInternalServerError{}
}

/*DeleteRegionsIDInternalServerError handles this case with default header values.

Generic error
*/
type DeleteRegionsIDInternalServerError struct {
	Payload *models.Message
}

func (o *DeleteRegionsIDInternalServerError) Error() string {
	return fmt.Sprintf("[DELETE /regions/{id}][%d] deleteRegionsIdInternalServerError  %+v", 500, o.Payload)
}

func (o *DeleteRegionsIDInternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Message)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
