// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	"github.com/fogatlas/client-go/models"
)

// DeleteMicroservicesIDReader is a Reader for the DeleteMicroservicesID structure.
type DeleteMicroservicesIDReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *DeleteMicroservicesIDReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 204:
		result := NewDeleteMicroservicesIDNoContent()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	case 400:
		result := NewDeleteMicroservicesIDBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	case 500:
		result := NewDeleteMicroservicesIDInternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewDeleteMicroservicesIDNoContent creates a DeleteMicroservicesIDNoContent with default headers values
func NewDeleteMicroservicesIDNoContent() *DeleteMicroservicesIDNoContent {
	return &DeleteMicroservicesIDNoContent{}
}

/*DeleteMicroservicesIDNoContent handles this case with default header values.

Microservice deleted
*/
type DeleteMicroservicesIDNoContent struct {
}

func (o *DeleteMicroservicesIDNoContent) Error() string {
	return fmt.Sprintf("[DELETE /microservices/{id}][%d] deleteMicroservicesIdNoContent ", 204)
}

func (o *DeleteMicroservicesIDNoContent) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewDeleteMicroservicesIDBadRequest creates a DeleteMicroservicesIDBadRequest with default headers values
func NewDeleteMicroservicesIDBadRequest() *DeleteMicroservicesIDBadRequest {
	return &DeleteMicroservicesIDBadRequest{}
}

/*DeleteMicroservicesIDBadRequest handles this case with default header values.

Invalid request
*/
type DeleteMicroservicesIDBadRequest struct {
	Payload *models.Message
}

func (o *DeleteMicroservicesIDBadRequest) Error() string {
	return fmt.Sprintf("[DELETE /microservices/{id}][%d] deleteMicroservicesIdBadRequest  %+v", 400, o.Payload)
}

func (o *DeleteMicroservicesIDBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Message)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewDeleteMicroservicesIDInternalServerError creates a DeleteMicroservicesIDInternalServerError with default headers values
func NewDeleteMicroservicesIDInternalServerError() *DeleteMicroservicesIDInternalServerError {
	return &DeleteMicroservicesIDInternalServerError{}
}

/*DeleteMicroservicesIDInternalServerError handles this case with default header values.

Generic error
*/
type DeleteMicroservicesIDInternalServerError struct {
	Payload *models.Message
}

func (o *DeleteMicroservicesIDInternalServerError) Error() string {
	return fmt.Sprintf("[DELETE /microservices/{id}][%d] deleteMicroservicesIdInternalServerError  %+v", 500, o.Payload)
}

func (o *DeleteMicroservicesIDInternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Message)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
