// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"
	"time"

	"golang.org/x/net/context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"
)

// NewDeleteRelationshipsIDParams creates a new DeleteRelationshipsIDParams object
// with the default values initialized.
func NewDeleteRelationshipsIDParams() *DeleteRelationshipsIDParams {
	var ()
	return &DeleteRelationshipsIDParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewDeleteRelationshipsIDParamsWithTimeout creates a new DeleteRelationshipsIDParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewDeleteRelationshipsIDParamsWithTimeout(timeout time.Duration) *DeleteRelationshipsIDParams {
	var ()
	return &DeleteRelationshipsIDParams{

		timeout: timeout,
	}
}

// NewDeleteRelationshipsIDParamsWithContext creates a new DeleteRelationshipsIDParams object
// with the default values initialized, and the ability to set a context for a request
func NewDeleteRelationshipsIDParamsWithContext(ctx context.Context) *DeleteRelationshipsIDParams {
	var ()
	return &DeleteRelationshipsIDParams{

		Context: ctx,
	}
}

// NewDeleteRelationshipsIDParamsWithHTTPClient creates a new DeleteRelationshipsIDParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewDeleteRelationshipsIDParamsWithHTTPClient(client *http.Client) *DeleteRelationshipsIDParams {
	var ()
	return &DeleteRelationshipsIDParams{
		HTTPClient: client,
	}
}

/*DeleteRelationshipsIDParams contains all the parameters to send to the API endpoint
for the delete relationships ID operation typically these are written to a http.Request
*/
type DeleteRelationshipsIDParams struct {

	/*ID*/
	ID string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the delete relationships ID params
func (o *DeleteRelationshipsIDParams) WithTimeout(timeout time.Duration) *DeleteRelationshipsIDParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the delete relationships ID params
func (o *DeleteRelationshipsIDParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the delete relationships ID params
func (o *DeleteRelationshipsIDParams) WithContext(ctx context.Context) *DeleteRelationshipsIDParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the delete relationships ID params
func (o *DeleteRelationshipsIDParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the delete relationships ID params
func (o *DeleteRelationshipsIDParams) WithHTTPClient(client *http.Client) *DeleteRelationshipsIDParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the delete relationships ID params
func (o *DeleteRelationshipsIDParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithID adds the id to the delete relationships ID params
func (o *DeleteRelationshipsIDParams) WithID(id string) *DeleteRelationshipsIDParams {
	o.SetID(id)
	return o
}

// SetID adds the id to the delete relationships ID params
func (o *DeleteRelationshipsIDParams) SetID(id string) {
	o.ID = id
}

// WriteToRequest writes these params to a swagger request
func (o *DeleteRelationshipsIDParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param id
	if err := r.SetPathParam("id", o.ID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
