// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"
	"time"

	"golang.org/x/net/context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"
)

// NewGetMicroservicesIDParams creates a new GetMicroservicesIDParams object
// with the default values initialized.
func NewGetMicroservicesIDParams() *GetMicroservicesIDParams {
	var ()
	return &GetMicroservicesIDParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewGetMicroservicesIDParamsWithTimeout creates a new GetMicroservicesIDParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewGetMicroservicesIDParamsWithTimeout(timeout time.Duration) *GetMicroservicesIDParams {
	var ()
	return &GetMicroservicesIDParams{

		timeout: timeout,
	}
}

// NewGetMicroservicesIDParamsWithContext creates a new GetMicroservicesIDParams object
// with the default values initialized, and the ability to set a context for a request
func NewGetMicroservicesIDParamsWithContext(ctx context.Context) *GetMicroservicesIDParams {
	var ()
	return &GetMicroservicesIDParams{

		Context: ctx,
	}
}

// NewGetMicroservicesIDParamsWithHTTPClient creates a new GetMicroservicesIDParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewGetMicroservicesIDParamsWithHTTPClient(client *http.Client) *GetMicroservicesIDParams {
	var ()
	return &GetMicroservicesIDParams{
		HTTPClient: client,
	}
}

/*GetMicroservicesIDParams contains all the parameters to send to the API endpoint
for the get microservices ID operation typically these are written to a http.Request
*/
type GetMicroservicesIDParams struct {

	/*ID*/
	ID string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the get microservices ID params
func (o *GetMicroservicesIDParams) WithTimeout(timeout time.Duration) *GetMicroservicesIDParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get microservices ID params
func (o *GetMicroservicesIDParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get microservices ID params
func (o *GetMicroservicesIDParams) WithContext(ctx context.Context) *GetMicroservicesIDParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get microservices ID params
func (o *GetMicroservicesIDParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get microservices ID params
func (o *GetMicroservicesIDParams) WithHTTPClient(client *http.Client) *GetMicroservicesIDParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get microservices ID params
func (o *GetMicroservicesIDParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithID adds the id to the get microservices ID params
func (o *GetMicroservicesIDParams) WithID(id string) *GetMicroservicesIDParams {
	o.SetID(id)
	return o
}

// SetID adds the id to the get microservices ID params
func (o *GetMicroservicesIDParams) SetID(id string) {
	o.ID = id
}

// WriteToRequest writes these params to a swagger request
func (o *GetMicroservicesIDParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param id
	if err := r.SetPathParam("id", o.ID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
