// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	"github.com/fogatlas/client-go/models"
)

// GetExternalendpointsReader is a Reader for the GetExternalendpoints structure.
type GetExternalendpointsReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetExternalendpointsReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewGetExternalendpointsOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	case 400:
		result := NewGetExternalendpointsBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	case 500:
		result := NewGetExternalendpointsInternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewGetExternalendpointsOK creates a GetExternalendpointsOK with default headers values
func NewGetExternalendpointsOK() *GetExternalendpointsOK {
	return &GetExternalendpointsOK{}
}

/*GetExternalendpointsOK handles this case with default header values.

Successfully returned the list of external endpoints
*/
type GetExternalendpointsOK struct {
	Payload *models.GetExternalendpointsOKBody
}

func (o *GetExternalendpointsOK) Error() string {
	return fmt.Sprintf("[GET /externalendpoints][%d] getExternalendpointsOK  %+v", 200, o.Payload)
}

func (o *GetExternalendpointsOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.GetExternalendpointsOKBody)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetExternalendpointsBadRequest creates a GetExternalendpointsBadRequest with default headers values
func NewGetExternalendpointsBadRequest() *GetExternalendpointsBadRequest {
	return &GetExternalendpointsBadRequest{}
}

/*GetExternalendpointsBadRequest handles this case with default header values.

Invalid request
*/
type GetExternalendpointsBadRequest struct {
	Payload *models.Message
}

func (o *GetExternalendpointsBadRequest) Error() string {
	return fmt.Sprintf("[GET /externalendpoints][%d] getExternalendpointsBadRequest  %+v", 400, o.Payload)
}

func (o *GetExternalendpointsBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Message)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetExternalendpointsInternalServerError creates a GetExternalendpointsInternalServerError with default headers values
func NewGetExternalendpointsInternalServerError() *GetExternalendpointsInternalServerError {
	return &GetExternalendpointsInternalServerError{}
}

/*GetExternalendpointsInternalServerError handles this case with default header values.

Generic error
*/
type GetExternalendpointsInternalServerError struct {
	Payload *models.Message
}

func (o *GetExternalendpointsInternalServerError) Error() string {
	return fmt.Sprintf("[GET /externalendpoints][%d] getExternalendpointsInternalServerError  %+v", 500, o.Payload)
}

func (o *GetExternalendpointsInternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Message)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
