// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	"github.com/fogatlas/client-go/models"
)

// GetRelationshipsReader is a Reader for the GetRelationships structure.
type GetRelationshipsReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetRelationshipsReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewGetRelationshipsOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	case 400:
		result := NewGetRelationshipsBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	case 500:
		result := NewGetRelationshipsInternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewGetRelationshipsOK creates a GetRelationshipsOK with default headers values
func NewGetRelationshipsOK() *GetRelationshipsOK {
	return &GetRelationshipsOK{}
}

/*GetRelationshipsOK handles this case with default header values.

Successfully returned the list of relationships
*/
type GetRelationshipsOK struct {
	Payload *models.GetRelationshipsOKBody
}

func (o *GetRelationshipsOK) Error() string {
	return fmt.Sprintf("[GET /relationships][%d] getRelationshipsOK  %+v", 200, o.Payload)
}

func (o *GetRelationshipsOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.GetRelationshipsOKBody)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetRelationshipsBadRequest creates a GetRelationshipsBadRequest with default headers values
func NewGetRelationshipsBadRequest() *GetRelationshipsBadRequest {
	return &GetRelationshipsBadRequest{}
}

/*GetRelationshipsBadRequest handles this case with default header values.

Invalid request
*/
type GetRelationshipsBadRequest struct {
	Payload *models.Message
}

func (o *GetRelationshipsBadRequest) Error() string {
	return fmt.Sprintf("[GET /relationships][%d] getRelationshipsBadRequest  %+v", 400, o.Payload)
}

func (o *GetRelationshipsBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Message)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetRelationshipsInternalServerError creates a GetRelationshipsInternalServerError with default headers values
func NewGetRelationshipsInternalServerError() *GetRelationshipsInternalServerError {
	return &GetRelationshipsInternalServerError{}
}

/*GetRelationshipsInternalServerError handles this case with default header values.

Generic error
*/
type GetRelationshipsInternalServerError struct {
	Payload *models.Message
}

func (o *GetRelationshipsInternalServerError) Error() string {
	return fmt.Sprintf("[GET /relationships][%d] getRelationshipsInternalServerError  %+v", 500, o.Payload)
}

func (o *GetRelationshipsInternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Message)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
