// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	"github.com/fogatlas/client-go/models"
)

// GetApplicationsIDReader is a Reader for the GetApplicationsID structure.
type GetApplicationsIDReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetApplicationsIDReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewGetApplicationsIDOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	case 400:
		result := NewGetApplicationsIDBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	case 500:
		result := NewGetApplicationsIDInternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewGetApplicationsIDOK creates a GetApplicationsIDOK with default headers values
func NewGetApplicationsIDOK() *GetApplicationsIDOK {
	return &GetApplicationsIDOK{}
}

/*GetApplicationsIDOK handles this case with default header values.

Successfully returned the given application
*/
type GetApplicationsIDOK struct {
	Payload *models.Application
}

func (o *GetApplicationsIDOK) Error() string {
	return fmt.Sprintf("[GET /applications/{id}][%d] getApplicationsIdOK  %+v", 200, o.Payload)
}

func (o *GetApplicationsIDOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Application)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetApplicationsIDBadRequest creates a GetApplicationsIDBadRequest with default headers values
func NewGetApplicationsIDBadRequest() *GetApplicationsIDBadRequest {
	return &GetApplicationsIDBadRequest{}
}

/*GetApplicationsIDBadRequest handles this case with default header values.

Invalid request
*/
type GetApplicationsIDBadRequest struct {
	Payload *models.Message
}

func (o *GetApplicationsIDBadRequest) Error() string {
	return fmt.Sprintf("[GET /applications/{id}][%d] getApplicationsIdBadRequest  %+v", 400, o.Payload)
}

func (o *GetApplicationsIDBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Message)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetApplicationsIDInternalServerError creates a GetApplicationsIDInternalServerError with default headers values
func NewGetApplicationsIDInternalServerError() *GetApplicationsIDInternalServerError {
	return &GetApplicationsIDInternalServerError{}
}

/*GetApplicationsIDInternalServerError handles this case with default header values.

Generic error
*/
type GetApplicationsIDInternalServerError struct {
	Payload *models.Message
}

func (o *GetApplicationsIDInternalServerError) Error() string {
	return fmt.Sprintf("[GET /applications/{id}][%d] getApplicationsIdInternalServerError  %+v", 500, o.Payload)
}

func (o *GetApplicationsIDInternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Message)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
