// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	"github.com/fogatlas/client-go/models"
)

// GetDataflowsIDReader is a Reader for the GetDataflowsID structure.
type GetDataflowsIDReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetDataflowsIDReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewGetDataflowsIDOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	case 400:
		result := NewGetDataflowsIDBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	case 500:
		result := NewGetDataflowsIDInternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewGetDataflowsIDOK creates a GetDataflowsIDOK with default headers values
func NewGetDataflowsIDOK() *GetDataflowsIDOK {
	return &GetDataflowsIDOK{}
}

/*GetDataflowsIDOK handles this case with default header values.

Successfully returned the dataflow
*/
type GetDataflowsIDOK struct {
	Payload *models.Dataflow
}

func (o *GetDataflowsIDOK) Error() string {
	return fmt.Sprintf("[GET /dataflows/{id}][%d] getDataflowsIdOK  %+v", 200, o.Payload)
}

func (o *GetDataflowsIDOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Dataflow)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetDataflowsIDBadRequest creates a GetDataflowsIDBadRequest with default headers values
func NewGetDataflowsIDBadRequest() *GetDataflowsIDBadRequest {
	return &GetDataflowsIDBadRequest{}
}

/*GetDataflowsIDBadRequest handles this case with default header values.

Invalid request
*/
type GetDataflowsIDBadRequest struct {
	Payload *models.Message
}

func (o *GetDataflowsIDBadRequest) Error() string {
	return fmt.Sprintf("[GET /dataflows/{id}][%d] getDataflowsIdBadRequest  %+v", 400, o.Payload)
}

func (o *GetDataflowsIDBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Message)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetDataflowsIDInternalServerError creates a GetDataflowsIDInternalServerError with default headers values
func NewGetDataflowsIDInternalServerError() *GetDataflowsIDInternalServerError {
	return &GetDataflowsIDInternalServerError{}
}

/*GetDataflowsIDInternalServerError handles this case with default header values.

Generic error
*/
type GetDataflowsIDInternalServerError struct {
	Payload *models.Message
}

func (o *GetDataflowsIDInternalServerError) Error() string {
	return fmt.Sprintf("[GET /dataflows/{id}][%d] getDataflowsIdInternalServerError  %+v", 500, o.Payload)
}

func (o *GetDataflowsIDInternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Message)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
