// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"
	"time"

	"golang.org/x/net/context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"
)

// NewGetDeploymentsNameParams creates a new GetDeploymentsNameParams object
// with the default values initialized.
func NewGetDeploymentsNameParams() *GetDeploymentsNameParams {
	var ()
	return &GetDeploymentsNameParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewGetDeploymentsNameParamsWithTimeout creates a new GetDeploymentsNameParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewGetDeploymentsNameParamsWithTimeout(timeout time.Duration) *GetDeploymentsNameParams {
	var ()
	return &GetDeploymentsNameParams{

		timeout: timeout,
	}
}

// NewGetDeploymentsNameParamsWithContext creates a new GetDeploymentsNameParams object
// with the default values initialized, and the ability to set a context for a request
func NewGetDeploymentsNameParamsWithContext(ctx context.Context) *GetDeploymentsNameParams {
	var ()
	return &GetDeploymentsNameParams{

		Context: ctx,
	}
}

// NewGetDeploymentsNameParamsWithHTTPClient creates a new GetDeploymentsNameParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewGetDeploymentsNameParamsWithHTTPClient(client *http.Client) *GetDeploymentsNameParams {
	var ()
	return &GetDeploymentsNameParams{
		HTTPClient: client,
	}
}

/*GetDeploymentsNameParams contains all the parameters to send to the API endpoint
for the get deployments name operation typically these are written to a http.Request
*/
type GetDeploymentsNameParams struct {

	/*Name*/
	Name string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the get deployments name params
func (o *GetDeploymentsNameParams) WithTimeout(timeout time.Duration) *GetDeploymentsNameParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get deployments name params
func (o *GetDeploymentsNameParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get deployments name params
func (o *GetDeploymentsNameParams) WithContext(ctx context.Context) *GetDeploymentsNameParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get deployments name params
func (o *GetDeploymentsNameParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get deployments name params
func (o *GetDeploymentsNameParams) WithHTTPClient(client *http.Client) *GetDeploymentsNameParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get deployments name params
func (o *GetDeploymentsNameParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithName adds the name to the get deployments name params
func (o *GetDeploymentsNameParams) WithName(name string) *GetDeploymentsNameParams {
	o.SetName(name)
	return o
}

// SetName adds the name to the get deployments name params
func (o *GetDeploymentsNameParams) SetName(name string) {
	o.Name = name
}

// WriteToRequest writes these params to a swagger request
func (o *GetDeploymentsNameParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param name
	if err := r.SetPathParam("name", o.Name); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
