// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"
	"time"

	"golang.org/x/net/context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"
)

// NewGetRelationshipsIDParams creates a new GetRelationshipsIDParams object
// with the default values initialized.
func NewGetRelationshipsIDParams() *GetRelationshipsIDParams {
	var ()
	return &GetRelationshipsIDParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewGetRelationshipsIDParamsWithTimeout creates a new GetRelationshipsIDParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewGetRelationshipsIDParamsWithTimeout(timeout time.Duration) *GetRelationshipsIDParams {
	var ()
	return &GetRelationshipsIDParams{

		timeout: timeout,
	}
}

// NewGetRelationshipsIDParamsWithContext creates a new GetRelationshipsIDParams object
// with the default values initialized, and the ability to set a context for a request
func NewGetRelationshipsIDParamsWithContext(ctx context.Context) *GetRelationshipsIDParams {
	var ()
	return &GetRelationshipsIDParams{

		Context: ctx,
	}
}

// NewGetRelationshipsIDParamsWithHTTPClient creates a new GetRelationshipsIDParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewGetRelationshipsIDParamsWithHTTPClient(client *http.Client) *GetRelationshipsIDParams {
	var ()
	return &GetRelationshipsIDParams{
		HTTPClient: client,
	}
}

/*GetRelationshipsIDParams contains all the parameters to send to the API endpoint
for the get relationships ID operation typically these are written to a http.Request
*/
type GetRelationshipsIDParams struct {

	/*ID*/
	ID string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the get relationships ID params
func (o *GetRelationshipsIDParams) WithTimeout(timeout time.Duration) *GetRelationshipsIDParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get relationships ID params
func (o *GetRelationshipsIDParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get relationships ID params
func (o *GetRelationshipsIDParams) WithContext(ctx context.Context) *GetRelationshipsIDParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get relationships ID params
func (o *GetRelationshipsIDParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get relationships ID params
func (o *GetRelationshipsIDParams) WithHTTPClient(client *http.Client) *GetRelationshipsIDParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get relationships ID params
func (o *GetRelationshipsIDParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithID adds the id to the get relationships ID params
func (o *GetRelationshipsIDParams) WithID(id string) *GetRelationshipsIDParams {
	o.SetID(id)
	return o
}

// SetID adds the id to the get relationships ID params
func (o *GetRelationshipsIDParams) SetID(id string) {
	o.ID = id
}

// WriteToRequest writes these params to a swagger request
func (o *GetRelationshipsIDParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param id
	if err := r.SetPathParam("id", o.ID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
