// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	"github.com/fogatlas/client-go/models"
)

// GetDynamicnodesIDReader is a Reader for the GetDynamicnodesID structure.
type GetDynamicnodesIDReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetDynamicnodesIDReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewGetDynamicnodesIDOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	case 400:
		result := NewGetDynamicnodesIDBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	case 500:
		result := NewGetDynamicnodesIDInternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewGetDynamicnodesIDOK creates a GetDynamicnodesIDOK with default headers values
func NewGetDynamicnodesIDOK() *GetDynamicnodesIDOK {
	return &GetDynamicnodesIDOK{}
}

/*GetDynamicnodesIDOK handles this case with default header values.

Successfully returned the dynamic node specified
*/
type GetDynamicnodesIDOK struct {
	Payload *models.DynamicNode
}

func (o *GetDynamicnodesIDOK) Error() string {
	return fmt.Sprintf("[GET /dynamicnodes/{id}][%d] getDynamicnodesIdOK  %+v", 200, o.Payload)
}

func (o *GetDynamicnodesIDOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.DynamicNode)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetDynamicnodesIDBadRequest creates a GetDynamicnodesIDBadRequest with default headers values
func NewGetDynamicnodesIDBadRequest() *GetDynamicnodesIDBadRequest {
	return &GetDynamicnodesIDBadRequest{}
}

/*GetDynamicnodesIDBadRequest handles this case with default header values.

Invalid request
*/
type GetDynamicnodesIDBadRequest struct {
	Payload *models.Message
}

func (o *GetDynamicnodesIDBadRequest) Error() string {
	return fmt.Sprintf("[GET /dynamicnodes/{id}][%d] getDynamicnodesIdBadRequest  %+v", 400, o.Payload)
}

func (o *GetDynamicnodesIDBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Message)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetDynamicnodesIDInternalServerError creates a GetDynamicnodesIDInternalServerError with default headers values
func NewGetDynamicnodesIDInternalServerError() *GetDynamicnodesIDInternalServerError {
	return &GetDynamicnodesIDInternalServerError{}
}

/*GetDynamicnodesIDInternalServerError handles this case with default header values.

Generic error
*/
type GetDynamicnodesIDInternalServerError struct {
	Payload *models.Message
}

func (o *GetDynamicnodesIDInternalServerError) Error() string {
	return fmt.Sprintf("[GET /dynamicnodes/{id}][%d] getDynamicnodesIdInternalServerError  %+v", 500, o.Payload)
}

func (o *GetDynamicnodesIDInternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Message)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
