// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	"github.com/fogatlas/client-go/models"
)

// GetThingsReader is a Reader for the GetThings structure.
type GetThingsReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetThingsReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewGetThingsOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	case 400:
		result := NewGetThingsBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	case 500:
		result := NewGetThingsInternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewGetThingsOK creates a GetThingsOK with default headers values
func NewGetThingsOK() *GetThingsOK {
	return &GetThingsOK{}
}

/*GetThingsOK handles this case with default header values.

Successfully returned the list of things
*/
type GetThingsOK struct {
	Payload *models.GetThingsOKBody
}

func (o *GetThingsOK) Error() string {
	return fmt.Sprintf("[GET /things][%d] getThingsOK  %+v", 200, o.Payload)
}

func (o *GetThingsOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.GetThingsOKBody)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetThingsBadRequest creates a GetThingsBadRequest with default headers values
func NewGetThingsBadRequest() *GetThingsBadRequest {
	return &GetThingsBadRequest{}
}

/*GetThingsBadRequest handles this case with default header values.

Invalid request
*/
type GetThingsBadRequest struct {
	Payload *models.Message
}

func (o *GetThingsBadRequest) Error() string {
	return fmt.Sprintf("[GET /things][%d] getThingsBadRequest  %+v", 400, o.Payload)
}

func (o *GetThingsBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Message)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetThingsInternalServerError creates a GetThingsInternalServerError with default headers values
func NewGetThingsInternalServerError() *GetThingsInternalServerError {
	return &GetThingsInternalServerError{}
}

/*GetThingsInternalServerError handles this case with default header values.

Generic error
*/
type GetThingsInternalServerError struct {
	Payload *models.Message
}

func (o *GetThingsInternalServerError) Error() string {
	return fmt.Sprintf("[GET /things][%d] getThingsInternalServerError  %+v", 500, o.Payload)
}

func (o *GetThingsInternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Message)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
