// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"
	"time"

	"golang.org/x/net/context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"
)

// NewGetNodesIDParams creates a new GetNodesIDParams object
// with the default values initialized.
func NewGetNodesIDParams() *GetNodesIDParams {
	var ()
	return &GetNodesIDParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewGetNodesIDParamsWithTimeout creates a new GetNodesIDParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewGetNodesIDParamsWithTimeout(timeout time.Duration) *GetNodesIDParams {
	var ()
	return &GetNodesIDParams{

		timeout: timeout,
	}
}

// NewGetNodesIDParamsWithContext creates a new GetNodesIDParams object
// with the default values initialized, and the ability to set a context for a request
func NewGetNodesIDParamsWithContext(ctx context.Context) *GetNodesIDParams {
	var ()
	return &GetNodesIDParams{

		Context: ctx,
	}
}

// NewGetNodesIDParamsWithHTTPClient creates a new GetNodesIDParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewGetNodesIDParamsWithHTTPClient(client *http.Client) *GetNodesIDParams {
	var ()
	return &GetNodesIDParams{
		HTTPClient: client,
	}
}

/*GetNodesIDParams contains all the parameters to send to the API endpoint
for the get nodes ID operation typically these are written to a http.Request
*/
type GetNodesIDParams struct {

	/*ID*/
	ID string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the get nodes ID params
func (o *GetNodesIDParams) WithTimeout(timeout time.Duration) *GetNodesIDParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get nodes ID params
func (o *GetNodesIDParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get nodes ID params
func (o *GetNodesIDParams) WithContext(ctx context.Context) *GetNodesIDParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get nodes ID params
func (o *GetNodesIDParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get nodes ID params
func (o *GetNodesIDParams) WithHTTPClient(client *http.Client) *GetNodesIDParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get nodes ID params
func (o *GetNodesIDParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithID adds the id to the get nodes ID params
func (o *GetNodesIDParams) WithID(id string) *GetNodesIDParams {
	o.SetID(id)
	return o
}

// SetID adds the id to the get nodes ID params
func (o *GetNodesIDParams) SetID(id string) {
	o.ID = id
}

// WriteToRequest writes these params to a swagger request
func (o *GetNodesIDParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param id
	if err := r.SetPathParam("id", o.ID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
