// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	"github.com/fogatlas/client-go/models"
)

// GetDeploymentsReader is a Reader for the GetDeployments structure.
type GetDeploymentsReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetDeploymentsReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewGetDeploymentsOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	case 400:
		result := NewGetDeploymentsBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	case 500:
		result := NewGetDeploymentsInternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewGetDeploymentsOK creates a GetDeploymentsOK with default headers values
func NewGetDeploymentsOK() *GetDeploymentsOK {
	return &GetDeploymentsOK{}
}

/*GetDeploymentsOK handles this case with default header values.

Successfully returned the list of deployment requests
*/
type GetDeploymentsOK struct {
	Payload *models.GetDeploymentsOKBody
}

func (o *GetDeploymentsOK) Error() string {
	return fmt.Sprintf("[GET /deployments][%d] getDeploymentsOK  %+v", 200, o.Payload)
}

func (o *GetDeploymentsOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.GetDeploymentsOKBody)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetDeploymentsBadRequest creates a GetDeploymentsBadRequest with default headers values
func NewGetDeploymentsBadRequest() *GetDeploymentsBadRequest {
	return &GetDeploymentsBadRequest{}
}

/*GetDeploymentsBadRequest handles this case with default header values.

Invalid request
*/
type GetDeploymentsBadRequest struct {
	Payload *models.Message
}

func (o *GetDeploymentsBadRequest) Error() string {
	return fmt.Sprintf("[GET /deployments][%d] getDeploymentsBadRequest  %+v", 400, o.Payload)
}

func (o *GetDeploymentsBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Message)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetDeploymentsInternalServerError creates a GetDeploymentsInternalServerError with default headers values
func NewGetDeploymentsInternalServerError() *GetDeploymentsInternalServerError {
	return &GetDeploymentsInternalServerError{}
}

/*GetDeploymentsInternalServerError handles this case with default header values.

Generic error
*/
type GetDeploymentsInternalServerError struct {
	Payload *models.Message
}

func (o *GetDeploymentsInternalServerError) Error() string {
	return fmt.Sprintf("[GET /deployments][%d] getDeploymentsInternalServerError  %+v", 500, o.Payload)
}

func (o *GetDeploymentsInternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Message)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
