// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"
	"time"

	"golang.org/x/net/context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"
)

// NewGetDynamicnodesParams creates a new GetDynamicnodesParams object
// with the default values initialized.
func NewGetDynamicnodesParams() *GetDynamicnodesParams {
	var ()
	return &GetDynamicnodesParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewGetDynamicnodesParamsWithTimeout creates a new GetDynamicnodesParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewGetDynamicnodesParamsWithTimeout(timeout time.Duration) *GetDynamicnodesParams {
	var ()
	return &GetDynamicnodesParams{

		timeout: timeout,
	}
}

// NewGetDynamicnodesParamsWithContext creates a new GetDynamicnodesParams object
// with the default values initialized, and the ability to set a context for a request
func NewGetDynamicnodesParamsWithContext(ctx context.Context) *GetDynamicnodesParams {
	var ()
	return &GetDynamicnodesParams{

		Context: ctx,
	}
}

// NewGetDynamicnodesParamsWithHTTPClient creates a new GetDynamicnodesParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewGetDynamicnodesParamsWithHTTPClient(client *http.Client) *GetDynamicnodesParams {
	var ()
	return &GetDynamicnodesParams{
		HTTPClient: client,
	}
}

/*GetDynamicnodesParams contains all the parameters to send to the API endpoint
for the get dynamicnodes operation typically these are written to a http.Request
*/
type GetDynamicnodesParams struct {

	/*RegionID
	  Returns dynamic nodes in the given region

	*/
	RegionID *string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the get dynamicnodes params
func (o *GetDynamicnodesParams) WithTimeout(timeout time.Duration) *GetDynamicnodesParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get dynamicnodes params
func (o *GetDynamicnodesParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get dynamicnodes params
func (o *GetDynamicnodesParams) WithContext(ctx context.Context) *GetDynamicnodesParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get dynamicnodes params
func (o *GetDynamicnodesParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get dynamicnodes params
func (o *GetDynamicnodesParams) WithHTTPClient(client *http.Client) *GetDynamicnodesParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get dynamicnodes params
func (o *GetDynamicnodesParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithRegionID adds the regionID to the get dynamicnodes params
func (o *GetDynamicnodesParams) WithRegionID(regionID *string) *GetDynamicnodesParams {
	o.SetRegionID(regionID)
	return o
}

// SetRegionID adds the regionId to the get dynamicnodes params
func (o *GetDynamicnodesParams) SetRegionID(regionID *string) {
	o.RegionID = regionID
}

// WriteToRequest writes these params to a swagger request
func (o *GetDynamicnodesParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if o.RegionID != nil {

		// query param region_id
		var qrRegionID string
		if o.RegionID != nil {
			qrRegionID = *o.RegionID
		}
		qRegionID := qrRegionID
		if qRegionID != "" {
			if err := r.SetQueryParam("region_id", qRegionID); err != nil {
				return err
			}
		}

	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
