// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"
	"time"

	"golang.org/x/net/context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"
)

// NewGetDataflowsParams creates a new GetDataflowsParams object
// with the default values initialized.
func NewGetDataflowsParams() *GetDataflowsParams {
	var ()
	return &GetDataflowsParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewGetDataflowsParamsWithTimeout creates a new GetDataflowsParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewGetDataflowsParamsWithTimeout(timeout time.Duration) *GetDataflowsParams {
	var ()
	return &GetDataflowsParams{

		timeout: timeout,
	}
}

// NewGetDataflowsParamsWithContext creates a new GetDataflowsParams object
// with the default values initialized, and the ability to set a context for a request
func NewGetDataflowsParamsWithContext(ctx context.Context) *GetDataflowsParams {
	var ()
	return &GetDataflowsParams{

		Context: ctx,
	}
}

// NewGetDataflowsParamsWithHTTPClient creates a new GetDataflowsParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewGetDataflowsParamsWithHTTPClient(client *http.Client) *GetDataflowsParams {
	var ()
	return &GetDataflowsParams{
		HTTPClient: client,
	}
}

/*GetDataflowsParams contains all the parameters to send to the API endpoint
for the get dataflows operation typically these are written to a http.Request
*/
type GetDataflowsParams struct {

	/*MicroserviceID
	  Returns dataflows starting from the given microservice

	*/
	MicroserviceID *string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the get dataflows params
func (o *GetDataflowsParams) WithTimeout(timeout time.Duration) *GetDataflowsParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get dataflows params
func (o *GetDataflowsParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get dataflows params
func (o *GetDataflowsParams) WithContext(ctx context.Context) *GetDataflowsParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get dataflows params
func (o *GetDataflowsParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get dataflows params
func (o *GetDataflowsParams) WithHTTPClient(client *http.Client) *GetDataflowsParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get dataflows params
func (o *GetDataflowsParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithMicroserviceID adds the microserviceID to the get dataflows params
func (o *GetDataflowsParams) WithMicroserviceID(microserviceID *string) *GetDataflowsParams {
	o.SetMicroserviceID(microserviceID)
	return o
}

// SetMicroserviceID adds the microserviceId to the get dataflows params
func (o *GetDataflowsParams) SetMicroserviceID(microserviceID *string) {
	o.MicroserviceID = microserviceID
}

// WriteToRequest writes these params to a swagger request
func (o *GetDataflowsParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if o.MicroserviceID != nil {

		// query param microservice_id
		var qrMicroserviceID string
		if o.MicroserviceID != nil {
			qrMicroserviceID = *o.MicroserviceID
		}
		qMicroserviceID := qrMicroserviceID
		if qMicroserviceID != "" {
			if err := r.SetQueryParam("microservice_id", qMicroserviceID); err != nil {
				return err
			}
		}

	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
