// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	"github.com/fogatlas/client-go/models"
)

// GetNodesReader is a Reader for the GetNodes structure.
type GetNodesReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetNodesReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewGetNodesOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	case 400:
		result := NewGetNodesBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	case 500:
		result := NewGetNodesInternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewGetNodesOK creates a GetNodesOK with default headers values
func NewGetNodesOK() *GetNodesOK {
	return &GetNodesOK{}
}

/*GetNodesOK handles this case with default header values.

Successfully returned the list of nodes
*/
type GetNodesOK struct {
	Payload *models.GetNodesOKBody
}

func (o *GetNodesOK) Error() string {
	return fmt.Sprintf("[GET /nodes][%d] getNodesOK  %+v", 200, o.Payload)
}

func (o *GetNodesOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.GetNodesOKBody)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetNodesBadRequest creates a GetNodesBadRequest with default headers values
func NewGetNodesBadRequest() *GetNodesBadRequest {
	return &GetNodesBadRequest{}
}

/*GetNodesBadRequest handles this case with default header values.

Invalid request
*/
type GetNodesBadRequest struct {
	Payload *models.Message
}

func (o *GetNodesBadRequest) Error() string {
	return fmt.Sprintf("[GET /nodes][%d] getNodesBadRequest  %+v", 400, o.Payload)
}

func (o *GetNodesBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Message)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetNodesInternalServerError creates a GetNodesInternalServerError with default headers values
func NewGetNodesInternalServerError() *GetNodesInternalServerError {
	return &GetNodesInternalServerError{}
}

/*GetNodesInternalServerError handles this case with default header values.

Generic error
*/
type GetNodesInternalServerError struct {
	Payload *models.Message
}

func (o *GetNodesInternalServerError) Error() string {
	return fmt.Sprintf("[GET /nodes][%d] getNodesInternalServerError  %+v", 500, o.Payload)
}

func (o *GetNodesInternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Message)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
