// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	"github.com/fogatlas/client-go/models"
)

// GetDataflowsReader is a Reader for the GetDataflows structure.
type GetDataflowsReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetDataflowsReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewGetDataflowsOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	case 400:
		result := NewGetDataflowsBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	case 500:
		result := NewGetDataflowsInternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewGetDataflowsOK creates a GetDataflowsOK with default headers values
func NewGetDataflowsOK() *GetDataflowsOK {
	return &GetDataflowsOK{}
}

/*GetDataflowsOK handles this case with default header values.

Successfully returned the list of dataflows
*/
type GetDataflowsOK struct {
	Payload *models.GetDataflowsOKBody
}

func (o *GetDataflowsOK) Error() string {
	return fmt.Sprintf("[GET /dataflows][%d] getDataflowsOK  %+v", 200, o.Payload)
}

func (o *GetDataflowsOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.GetDataflowsOKBody)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetDataflowsBadRequest creates a GetDataflowsBadRequest with default headers values
func NewGetDataflowsBadRequest() *GetDataflowsBadRequest {
	return &GetDataflowsBadRequest{}
}

/*GetDataflowsBadRequest handles this case with default header values.

Invalid request
*/
type GetDataflowsBadRequest struct {
	Payload *models.Message
}

func (o *GetDataflowsBadRequest) Error() string {
	return fmt.Sprintf("[GET /dataflows][%d] getDataflowsBadRequest  %+v", 400, o.Payload)
}

func (o *GetDataflowsBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Message)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetDataflowsInternalServerError creates a GetDataflowsInternalServerError with default headers values
func NewGetDataflowsInternalServerError() *GetDataflowsInternalServerError {
	return &GetDataflowsInternalServerError{}
}

/*GetDataflowsInternalServerError handles this case with default header values.

Generic error
*/
type GetDataflowsInternalServerError struct {
	Payload *models.Message
}

func (o *GetDataflowsInternalServerError) Error() string {
	return fmt.Sprintf("[GET /dataflows][%d] getDataflowsInternalServerError  %+v", 500, o.Payload)
}

func (o *GetDataflowsInternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Message)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
