// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"
	"time"

	"golang.org/x/net/context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"
)

// NewGetDataflowsIDParams creates a new GetDataflowsIDParams object
// with the default values initialized.
func NewGetDataflowsIDParams() *GetDataflowsIDParams {
	var ()
	return &GetDataflowsIDParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewGetDataflowsIDParamsWithTimeout creates a new GetDataflowsIDParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewGetDataflowsIDParamsWithTimeout(timeout time.Duration) *GetDataflowsIDParams {
	var ()
	return &GetDataflowsIDParams{

		timeout: timeout,
	}
}

// NewGetDataflowsIDParamsWithContext creates a new GetDataflowsIDParams object
// with the default values initialized, and the ability to set a context for a request
func NewGetDataflowsIDParamsWithContext(ctx context.Context) *GetDataflowsIDParams {
	var ()
	return &GetDataflowsIDParams{

		Context: ctx,
	}
}

// NewGetDataflowsIDParamsWithHTTPClient creates a new GetDataflowsIDParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewGetDataflowsIDParamsWithHTTPClient(client *http.Client) *GetDataflowsIDParams {
	var ()
	return &GetDataflowsIDParams{
		HTTPClient: client,
	}
}

/*GetDataflowsIDParams contains all the parameters to send to the API endpoint
for the get dataflows ID operation typically these are written to a http.Request
*/
type GetDataflowsIDParams struct {

	/*ID*/
	ID string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the get dataflows ID params
func (o *GetDataflowsIDParams) WithTimeout(timeout time.Duration) *GetDataflowsIDParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get dataflows ID params
func (o *GetDataflowsIDParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get dataflows ID params
func (o *GetDataflowsIDParams) WithContext(ctx context.Context) *GetDataflowsIDParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get dataflows ID params
func (o *GetDataflowsIDParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get dataflows ID params
func (o *GetDataflowsIDParams) WithHTTPClient(client *http.Client) *GetDataflowsIDParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get dataflows ID params
func (o *GetDataflowsIDParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithID adds the id to the get dataflows ID params
func (o *GetDataflowsIDParams) WithID(id string) *GetDataflowsIDParams {
	o.SetID(id)
	return o
}

// SetID adds the id to the get dataflows ID params
func (o *GetDataflowsIDParams) SetID(id string) {
	o.ID = id
}

// WriteToRequest writes these params to a swagger request
func (o *GetDataflowsIDParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param id
	if err := r.SetPathParam("id", o.ID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
