// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"
	"time"

	"golang.org/x/net/context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"
)

// NewGetNodesParams creates a new GetNodesParams object
// with the default values initialized.
func NewGetNodesParams() *GetNodesParams {
	var ()
	return &GetNodesParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewGetNodesParamsWithTimeout creates a new GetNodesParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewGetNodesParamsWithTimeout(timeout time.Duration) *GetNodesParams {
	var ()
	return &GetNodesParams{

		timeout: timeout,
	}
}

// NewGetNodesParamsWithContext creates a new GetNodesParams object
// with the default values initialized, and the ability to set a context for a request
func NewGetNodesParamsWithContext(ctx context.Context) *GetNodesParams {
	var ()
	return &GetNodesParams{

		Context: ctx,
	}
}

// NewGetNodesParamsWithHTTPClient creates a new GetNodesParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewGetNodesParamsWithHTTPClient(client *http.Client) *GetNodesParams {
	var ()
	return &GetNodesParams{
		HTTPClient: client,
	}
}

/*GetNodesParams contains all the parameters to send to the API endpoint
for the get nodes operation typically these are written to a http.Request
*/
type GetNodesParams struct {

	/*RegionID
	  Returns nodes in the given region

	*/
	RegionID *string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the get nodes params
func (o *GetNodesParams) WithTimeout(timeout time.Duration) *GetNodesParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get nodes params
func (o *GetNodesParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get nodes params
func (o *GetNodesParams) WithContext(ctx context.Context) *GetNodesParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get nodes params
func (o *GetNodesParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get nodes params
func (o *GetNodesParams) WithHTTPClient(client *http.Client) *GetNodesParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get nodes params
func (o *GetNodesParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithRegionID adds the regionID to the get nodes params
func (o *GetNodesParams) WithRegionID(regionID *string) *GetNodesParams {
	o.SetRegionID(regionID)
	return o
}

// SetRegionID adds the regionId to the get nodes params
func (o *GetNodesParams) SetRegionID(regionID *string) {
	o.RegionID = regionID
}

// WriteToRequest writes these params to a swagger request
func (o *GetNodesParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if o.RegionID != nil {

		// query param region_id
		var qrRegionID string
		if o.RegionID != nil {
			qrRegionID = *o.RegionID
		}
		qRegionID := qrRegionID
		if qRegionID != "" {
			if err := r.SetQueryParam("region_id", qRegionID); err != nil {
				return err
			}
		}

	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
