// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	"github.com/fogatlas/client-go/models"
)

// GetRegionsIDReader is a Reader for the GetRegionsID structure.
type GetRegionsIDReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetRegionsIDReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewGetRegionsIDOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	case 400:
		result := NewGetRegionsIDBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	case 500:
		result := NewGetRegionsIDInternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewGetRegionsIDOK creates a GetRegionsIDOK with default headers values
func NewGetRegionsIDOK() *GetRegionsIDOK {
	return &GetRegionsIDOK{}
}

/*GetRegionsIDOK handles this case with default header values.

Successfully returned the given region
*/
type GetRegionsIDOK struct {
	Payload *models.Region
}

func (o *GetRegionsIDOK) Error() string {
	return fmt.Sprintf("[GET /regions/{id}][%d] getRegionsIdOK  %+v", 200, o.Payload)
}

func (o *GetRegionsIDOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Region)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetRegionsIDBadRequest creates a GetRegionsIDBadRequest with default headers values
func NewGetRegionsIDBadRequest() *GetRegionsIDBadRequest {
	return &GetRegionsIDBadRequest{}
}

/*GetRegionsIDBadRequest handles this case with default header values.

Invalid request
*/
type GetRegionsIDBadRequest struct {
	Payload *models.Message
}

func (o *GetRegionsIDBadRequest) Error() string {
	return fmt.Sprintf("[GET /regions/{id}][%d] getRegionsIdBadRequest  %+v", 400, o.Payload)
}

func (o *GetRegionsIDBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Message)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetRegionsIDInternalServerError creates a GetRegionsIDInternalServerError with default headers values
func NewGetRegionsIDInternalServerError() *GetRegionsIDInternalServerError {
	return &GetRegionsIDInternalServerError{}
}

/*GetRegionsIDInternalServerError handles this case with default header values.

Generic error
*/
type GetRegionsIDInternalServerError struct {
	Payload *models.Message
}

func (o *GetRegionsIDInternalServerError) Error() string {
	return fmt.Sprintf("[GET /regions/{id}][%d] getRegionsIdInternalServerError  %+v", 500, o.Payload)
}

func (o *GetRegionsIDInternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Message)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
