// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"
	"time"

	"golang.org/x/net/context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"
)

// NewGetDeploymentsParams creates a new GetDeploymentsParams object
// with the default values initialized.
func NewGetDeploymentsParams() *GetDeploymentsParams {
	var ()
	return &GetDeploymentsParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewGetDeploymentsParamsWithTimeout creates a new GetDeploymentsParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewGetDeploymentsParamsWithTimeout(timeout time.Duration) *GetDeploymentsParams {
	var ()
	return &GetDeploymentsParams{

		timeout: timeout,
	}
}

// NewGetDeploymentsParamsWithContext creates a new GetDeploymentsParams object
// with the default values initialized, and the ability to set a context for a request
func NewGetDeploymentsParamsWithContext(ctx context.Context) *GetDeploymentsParams {
	var ()
	return &GetDeploymentsParams{

		Context: ctx,
	}
}

// NewGetDeploymentsParamsWithHTTPClient creates a new GetDeploymentsParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewGetDeploymentsParamsWithHTTPClient(client *http.Client) *GetDeploymentsParams {
	var ()
	return &GetDeploymentsParams{
		HTTPClient: client,
	}
}

/*GetDeploymentsParams contains all the parameters to send to the API endpoint
for the get deployments operation typically these are written to a http.Request
*/
type GetDeploymentsParams struct {

	/*Status
	  Returns deployments with a given status

	*/
	Status *string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the get deployments params
func (o *GetDeploymentsParams) WithTimeout(timeout time.Duration) *GetDeploymentsParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get deployments params
func (o *GetDeploymentsParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get deployments params
func (o *GetDeploymentsParams) WithContext(ctx context.Context) *GetDeploymentsParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get deployments params
func (o *GetDeploymentsParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get deployments params
func (o *GetDeploymentsParams) WithHTTPClient(client *http.Client) *GetDeploymentsParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get deployments params
func (o *GetDeploymentsParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithStatus adds the status to the get deployments params
func (o *GetDeploymentsParams) WithStatus(status *string) *GetDeploymentsParams {
	o.SetStatus(status)
	return o
}

// SetStatus adds the status to the get deployments params
func (o *GetDeploymentsParams) SetStatus(status *string) {
	o.Status = status
}

// WriteToRequest writes these params to a swagger request
func (o *GetDeploymentsParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if o.Status != nil {

		// query param status
		var qrStatus string
		if o.Status != nil {
			qrStatus = *o.Status
		}
		qStatus := qrStatus
		if qStatus != "" {
			if err := r.SetQueryParam("status", qStatus); err != nil {
				return err
			}
		}

	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
