// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	"github.com/fogatlas/client-go/models"
)

// GetThingsIDReader is a Reader for the GetThingsID structure.
type GetThingsIDReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetThingsIDReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewGetThingsIDOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	case 400:
		result := NewGetThingsIDBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	case 500:
		result := NewGetThingsIDInternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewGetThingsIDOK creates a GetThingsIDOK with default headers values
func NewGetThingsIDOK() *GetThingsIDOK {
	return &GetThingsIDOK{}
}

/*GetThingsIDOK handles this case with default header values.

Successfully returned the thing
*/
type GetThingsIDOK struct {
	Payload *models.Thing
}

func (o *GetThingsIDOK) Error() string {
	return fmt.Sprintf("[GET /things/{id}][%d] getThingsIdOK  %+v", 200, o.Payload)
}

func (o *GetThingsIDOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Thing)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetThingsIDBadRequest creates a GetThingsIDBadRequest with default headers values
func NewGetThingsIDBadRequest() *GetThingsIDBadRequest {
	return &GetThingsIDBadRequest{}
}

/*GetThingsIDBadRequest handles this case with default header values.

Invalid request
*/
type GetThingsIDBadRequest struct {
	Payload *models.Message
}

func (o *GetThingsIDBadRequest) Error() string {
	return fmt.Sprintf("[GET /things/{id}][%d] getThingsIdBadRequest  %+v", 400, o.Payload)
}

func (o *GetThingsIDBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Message)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetThingsIDInternalServerError creates a GetThingsIDInternalServerError with default headers values
func NewGetThingsIDInternalServerError() *GetThingsIDInternalServerError {
	return &GetThingsIDInternalServerError{}
}

/*GetThingsIDInternalServerError handles this case with default header values.

Generic error
*/
type GetThingsIDInternalServerError struct {
	Payload *models.Message
}

func (o *GetThingsIDInternalServerError) Error() string {
	return fmt.Sprintf("[GET /things/{id}][%d] getThingsIdInternalServerError  %+v", 500, o.Payload)
}

func (o *GetThingsIDInternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Message)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
