// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"
	"time"

	"golang.org/x/net/context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"
)

// NewGetExternalendpointsParams creates a new GetExternalendpointsParams object
// with the default values initialized.
func NewGetExternalendpointsParams() *GetExternalendpointsParams {
	var ()
	return &GetExternalendpointsParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewGetExternalendpointsParamsWithTimeout creates a new GetExternalendpointsParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewGetExternalendpointsParamsWithTimeout(timeout time.Duration) *GetExternalendpointsParams {
	var ()
	return &GetExternalendpointsParams{

		timeout: timeout,
	}
}

// NewGetExternalendpointsParamsWithContext creates a new GetExternalendpointsParams object
// with the default values initialized, and the ability to set a context for a request
func NewGetExternalendpointsParamsWithContext(ctx context.Context) *GetExternalendpointsParams {
	var ()
	return &GetExternalendpointsParams{

		Context: ctx,
	}
}

// NewGetExternalendpointsParamsWithHTTPClient creates a new GetExternalendpointsParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewGetExternalendpointsParamsWithHTTPClient(client *http.Client) *GetExternalendpointsParams {
	var ()
	return &GetExternalendpointsParams{
		HTTPClient: client,
	}
}

/*GetExternalendpointsParams contains all the parameters to send to the API endpoint
for the get externalendpoints operation typically these are written to a http.Request
*/
type GetExternalendpointsParams struct {

	/*RegionID
	  Returns the external endpoints in the given region

	*/
	RegionID *string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the get externalendpoints params
func (o *GetExternalendpointsParams) WithTimeout(timeout time.Duration) *GetExternalendpointsParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get externalendpoints params
func (o *GetExternalendpointsParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get externalendpoints params
func (o *GetExternalendpointsParams) WithContext(ctx context.Context) *GetExternalendpointsParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get externalendpoints params
func (o *GetExternalendpointsParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get externalendpoints params
func (o *GetExternalendpointsParams) WithHTTPClient(client *http.Client) *GetExternalendpointsParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get externalendpoints params
func (o *GetExternalendpointsParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithRegionID adds the regionID to the get externalendpoints params
func (o *GetExternalendpointsParams) WithRegionID(regionID *string) *GetExternalendpointsParams {
	o.SetRegionID(regionID)
	return o
}

// SetRegionID adds the regionId to the get externalendpoints params
func (o *GetExternalendpointsParams) SetRegionID(regionID *string) {
	o.RegionID = regionID
}

// WriteToRequest writes these params to a swagger request
func (o *GetExternalendpointsParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if o.RegionID != nil {

		// query param region_id
		var qrRegionID string
		if o.RegionID != nil {
			qrRegionID = *o.RegionID
		}
		qRegionID := qrRegionID
		if qRegionID != "" {
			if err := r.SetQueryParam("region_id", qRegionID); err != nil {
				return err
			}
		}

	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
