// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"
	"time"

	"golang.org/x/net/context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"
)

// NewGetRelationshipsParams creates a new GetRelationshipsParams object
// with the default values initialized.
func NewGetRelationshipsParams() *GetRelationshipsParams {
	var ()
	return &GetRelationshipsParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewGetRelationshipsParamsWithTimeout creates a new GetRelationshipsParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewGetRelationshipsParamsWithTimeout(timeout time.Duration) *GetRelationshipsParams {
	var ()
	return &GetRelationshipsParams{

		timeout: timeout,
	}
}

// NewGetRelationshipsParamsWithContext creates a new GetRelationshipsParams object
// with the default values initialized, and the ability to set a context for a request
func NewGetRelationshipsParamsWithContext(ctx context.Context) *GetRelationshipsParams {
	var ()
	return &GetRelationshipsParams{

		Context: ctx,
	}
}

// NewGetRelationshipsParamsWithHTTPClient creates a new GetRelationshipsParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewGetRelationshipsParamsWithHTTPClient(client *http.Client) *GetRelationshipsParams {
	var ()
	return &GetRelationshipsParams{
		HTTPClient: client,
	}
}

/*GetRelationshipsParams contains all the parameters to send to the API endpoint
for the get relationships operation typically these are written to a http.Request
*/
type GetRelationshipsParams struct {

	/*RegionID
	  Returns relationships starting from the given region

	*/
	RegionID *string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the get relationships params
func (o *GetRelationshipsParams) WithTimeout(timeout time.Duration) *GetRelationshipsParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get relationships params
func (o *GetRelationshipsParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get relationships params
func (o *GetRelationshipsParams) WithContext(ctx context.Context) *GetRelationshipsParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get relationships params
func (o *GetRelationshipsParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get relationships params
func (o *GetRelationshipsParams) WithHTTPClient(client *http.Client) *GetRelationshipsParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get relationships params
func (o *GetRelationshipsParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithRegionID adds the regionID to the get relationships params
func (o *GetRelationshipsParams) WithRegionID(regionID *string) *GetRelationshipsParams {
	o.SetRegionID(regionID)
	return o
}

// SetRegionID adds the regionId to the get relationships params
func (o *GetRelationshipsParams) SetRegionID(regionID *string) {
	o.RegionID = regionID
}

// WriteToRequest writes these params to a swagger request
func (o *GetRelationshipsParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if o.RegionID != nil {

		// query param region_id
		var qrRegionID string
		if o.RegionID != nil {
			qrRegionID = *o.RegionID
		}
		qRegionID := qrRegionID
		if qRegionID != "" {
			if err := r.SetQueryParam("region_id", qRegionID); err != nil {
				return err
			}
		}

	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
