// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	"github.com/fogatlas/client-go/models"
)

// GetDynamicnodesReader is a Reader for the GetDynamicnodes structure.
type GetDynamicnodesReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetDynamicnodesReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewGetDynamicnodesOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	case 400:
		result := NewGetDynamicnodesBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	case 500:
		result := NewGetDynamicnodesInternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewGetDynamicnodesOK creates a GetDynamicnodesOK with default headers values
func NewGetDynamicnodesOK() *GetDynamicnodesOK {
	return &GetDynamicnodesOK{}
}

/*GetDynamicnodesOK handles this case with default header values.

Successfully returned the list of dynamic nodes
*/
type GetDynamicnodesOK struct {
	Payload *models.GetDynamicnodesOKBody
}

func (o *GetDynamicnodesOK) Error() string {
	return fmt.Sprintf("[GET /dynamicnodes][%d] getDynamicnodesOK  %+v", 200, o.Payload)
}

func (o *GetDynamicnodesOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.GetDynamicnodesOKBody)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetDynamicnodesBadRequest creates a GetDynamicnodesBadRequest with default headers values
func NewGetDynamicnodesBadRequest() *GetDynamicnodesBadRequest {
	return &GetDynamicnodesBadRequest{}
}

/*GetDynamicnodesBadRequest handles this case with default header values.

Invalid request
*/
type GetDynamicnodesBadRequest struct {
	Payload *models.Message
}

func (o *GetDynamicnodesBadRequest) Error() string {
	return fmt.Sprintf("[GET /dynamicnodes][%d] getDynamicnodesBadRequest  %+v", 400, o.Payload)
}

func (o *GetDynamicnodesBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Message)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetDynamicnodesInternalServerError creates a GetDynamicnodesInternalServerError with default headers values
func NewGetDynamicnodesInternalServerError() *GetDynamicnodesInternalServerError {
	return &GetDynamicnodesInternalServerError{}
}

/*GetDynamicnodesInternalServerError handles this case with default header values.

Generic error
*/
type GetDynamicnodesInternalServerError struct {
	Payload *models.Message
}

func (o *GetDynamicnodesInternalServerError) Error() string {
	return fmt.Sprintf("[GET /dynamicnodes][%d] getDynamicnodesInternalServerError  %+v", 500, o.Payload)
}

func (o *GetDynamicnodesInternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Message)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
