// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	"github.com/fogatlas/client-go/models"
)

// GetRelationshipsIDReader is a Reader for the GetRelationshipsID structure.
type GetRelationshipsIDReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetRelationshipsIDReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewGetRelationshipsIDOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	case 400:
		result := NewGetRelationshipsIDBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	case 500:
		result := NewGetRelationshipsIDInternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewGetRelationshipsIDOK creates a GetRelationshipsIDOK with default headers values
func NewGetRelationshipsIDOK() *GetRelationshipsIDOK {
	return &GetRelationshipsIDOK{}
}

/*GetRelationshipsIDOK handles this case with default header values.

Successfully returned the relationship
*/
type GetRelationshipsIDOK struct {
	Payload *models.Relationship
}

func (o *GetRelationshipsIDOK) Error() string {
	return fmt.Sprintf("[GET /relationships/{id}][%d] getRelationshipsIdOK  %+v", 200, o.Payload)
}

func (o *GetRelationshipsIDOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Relationship)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetRelationshipsIDBadRequest creates a GetRelationshipsIDBadRequest with default headers values
func NewGetRelationshipsIDBadRequest() *GetRelationshipsIDBadRequest {
	return &GetRelationshipsIDBadRequest{}
}

/*GetRelationshipsIDBadRequest handles this case with default header values.

Invalid request
*/
type GetRelationshipsIDBadRequest struct {
	Payload *models.Message
}

func (o *GetRelationshipsIDBadRequest) Error() string {
	return fmt.Sprintf("[GET /relationships/{id}][%d] getRelationshipsIdBadRequest  %+v", 400, o.Payload)
}

func (o *GetRelationshipsIDBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Message)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetRelationshipsIDInternalServerError creates a GetRelationshipsIDInternalServerError with default headers values
func NewGetRelationshipsIDInternalServerError() *GetRelationshipsIDInternalServerError {
	return &GetRelationshipsIDInternalServerError{}
}

/*GetRelationshipsIDInternalServerError handles this case with default header values.

Generic error
*/
type GetRelationshipsIDInternalServerError struct {
	Payload *models.Message
}

func (o *GetRelationshipsIDInternalServerError) Error() string {
	return fmt.Sprintf("[GET /relationships/{id}][%d] getRelationshipsIdInternalServerError  %+v", 500, o.Payload)
}

func (o *GetRelationshipsIDInternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Message)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
