// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"
	"time"

	"golang.org/x/net/context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"

	"github.com/fogatlas/client-go/models"
)

// NewPatchDeploymentsNameParams creates a new PatchDeploymentsNameParams object
// with the default values initialized.
func NewPatchDeploymentsNameParams() *PatchDeploymentsNameParams {
	var ()
	return &PatchDeploymentsNameParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewPatchDeploymentsNameParamsWithTimeout creates a new PatchDeploymentsNameParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewPatchDeploymentsNameParamsWithTimeout(timeout time.Duration) *PatchDeploymentsNameParams {
	var ()
	return &PatchDeploymentsNameParams{

		timeout: timeout,
	}
}

// NewPatchDeploymentsNameParamsWithContext creates a new PatchDeploymentsNameParams object
// with the default values initialized, and the ability to set a context for a request
func NewPatchDeploymentsNameParamsWithContext(ctx context.Context) *PatchDeploymentsNameParams {
	var ()
	return &PatchDeploymentsNameParams{

		Context: ctx,
	}
}

// NewPatchDeploymentsNameParamsWithHTTPClient creates a new PatchDeploymentsNameParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewPatchDeploymentsNameParamsWithHTTPClient(client *http.Client) *PatchDeploymentsNameParams {
	var ()
	return &PatchDeploymentsNameParams{
		HTTPClient: client,
	}
}

/*PatchDeploymentsNameParams contains all the parameters to send to the API endpoint
for the patch deployments name operation typically these are written to a http.Request
*/
type PatchDeploymentsNameParams struct {

	/*PatchStatus*/
	PatchStatus *models.PatchStatus
	/*Name*/
	Name string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the patch deployments name params
func (o *PatchDeploymentsNameParams) WithTimeout(timeout time.Duration) *PatchDeploymentsNameParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the patch deployments name params
func (o *PatchDeploymentsNameParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the patch deployments name params
func (o *PatchDeploymentsNameParams) WithContext(ctx context.Context) *PatchDeploymentsNameParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the patch deployments name params
func (o *PatchDeploymentsNameParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the patch deployments name params
func (o *PatchDeploymentsNameParams) WithHTTPClient(client *http.Client) *PatchDeploymentsNameParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the patch deployments name params
func (o *PatchDeploymentsNameParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithPatchStatus adds the patchStatus to the patch deployments name params
func (o *PatchDeploymentsNameParams) WithPatchStatus(patchStatus *models.PatchStatus) *PatchDeploymentsNameParams {
	o.SetPatchStatus(patchStatus)
	return o
}

// SetPatchStatus adds the patchStatus to the patch deployments name params
func (o *PatchDeploymentsNameParams) SetPatchStatus(patchStatus *models.PatchStatus) {
	o.PatchStatus = patchStatus
}

// WithName adds the name to the patch deployments name params
func (o *PatchDeploymentsNameParams) WithName(name string) *PatchDeploymentsNameParams {
	o.SetName(name)
	return o
}

// SetName adds the name to the patch deployments name params
func (o *PatchDeploymentsNameParams) SetName(name string) {
	o.Name = name
}

// WriteToRequest writes these params to a swagger request
func (o *PatchDeploymentsNameParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if o.PatchStatus != nil {
		if err := r.SetBodyParam(o.PatchStatus); err != nil {
			return err
		}
	}

	// path param name
	if err := r.SetPathParam("name", o.Name); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
