// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	"github.com/fogatlas/client-go/models"
)

// PutMicroservicesIDReader is a Reader for the PutMicroservicesID structure.
type PutMicroservicesIDReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *PutMicroservicesIDReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 201:
		result := NewPutMicroservicesIDCreated()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	case 400:
		result := NewPutMicroservicesIDBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	case 500:
		result := NewPutMicroservicesIDInternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewPutMicroservicesIDCreated creates a PutMicroservicesIDCreated with default headers values
func NewPutMicroservicesIDCreated() *PutMicroservicesIDCreated {
	return &PutMicroservicesIDCreated{}
}

/*PutMicroservicesIDCreated handles this case with default header values.

Created
*/
type PutMicroservicesIDCreated struct {
}

func (o *PutMicroservicesIDCreated) Error() string {
	return fmt.Sprintf("[PUT /microservices/{id}][%d] putMicroservicesIdCreated ", 201)
}

func (o *PutMicroservicesIDCreated) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewPutMicroservicesIDBadRequest creates a PutMicroservicesIDBadRequest with default headers values
func NewPutMicroservicesIDBadRequest() *PutMicroservicesIDBadRequest {
	return &PutMicroservicesIDBadRequest{}
}

/*PutMicroservicesIDBadRequest handles this case with default header values.

Invalid request
*/
type PutMicroservicesIDBadRequest struct {
	Payload *models.Message
}

func (o *PutMicroservicesIDBadRequest) Error() string {
	return fmt.Sprintf("[PUT /microservices/{id}][%d] putMicroservicesIdBadRequest  %+v", 400, o.Payload)
}

func (o *PutMicroservicesIDBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Message)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewPutMicroservicesIDInternalServerError creates a PutMicroservicesIDInternalServerError with default headers values
func NewPutMicroservicesIDInternalServerError() *PutMicroservicesIDInternalServerError {
	return &PutMicroservicesIDInternalServerError{}
}

/*PutMicroservicesIDInternalServerError handles this case with default header values.

Generic error
*/
type PutMicroservicesIDInternalServerError struct {
	Payload *models.Message
}

func (o *PutMicroservicesIDInternalServerError) Error() string {
	return fmt.Sprintf("[PUT /microservices/{id}][%d] putMicroservicesIdInternalServerError  %+v", 500, o.Payload)
}

func (o *PutMicroservicesIDInternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Message)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
