// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"
	"time"

	"golang.org/x/net/context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"

	"github.com/fogatlas/client-go/models"
)

// NewPutApplicationsIDParams creates a new PutApplicationsIDParams object
// with the default values initialized.
func NewPutApplicationsIDParams() *PutApplicationsIDParams {
	var ()
	return &PutApplicationsIDParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewPutApplicationsIDParamsWithTimeout creates a new PutApplicationsIDParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewPutApplicationsIDParamsWithTimeout(timeout time.Duration) *PutApplicationsIDParams {
	var ()
	return &PutApplicationsIDParams{

		timeout: timeout,
	}
}

// NewPutApplicationsIDParamsWithContext creates a new PutApplicationsIDParams object
// with the default values initialized, and the ability to set a context for a request
func NewPutApplicationsIDParamsWithContext(ctx context.Context) *PutApplicationsIDParams {
	var ()
	return &PutApplicationsIDParams{

		Context: ctx,
	}
}

// NewPutApplicationsIDParamsWithHTTPClient creates a new PutApplicationsIDParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewPutApplicationsIDParamsWithHTTPClient(client *http.Client) *PutApplicationsIDParams {
	var ()
	return &PutApplicationsIDParams{
		HTTPClient: client,
	}
}

/*PutApplicationsIDParams contains all the parameters to send to the API endpoint
for the put applications ID operation typically these are written to a http.Request
*/
type PutApplicationsIDParams struct {

	/*Application*/
	Application *models.Application
	/*ID*/
	ID string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the put applications ID params
func (o *PutApplicationsIDParams) WithTimeout(timeout time.Duration) *PutApplicationsIDParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the put applications ID params
func (o *PutApplicationsIDParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the put applications ID params
func (o *PutApplicationsIDParams) WithContext(ctx context.Context) *PutApplicationsIDParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the put applications ID params
func (o *PutApplicationsIDParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the put applications ID params
func (o *PutApplicationsIDParams) WithHTTPClient(client *http.Client) *PutApplicationsIDParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the put applications ID params
func (o *PutApplicationsIDParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithApplication adds the application to the put applications ID params
func (o *PutApplicationsIDParams) WithApplication(application *models.Application) *PutApplicationsIDParams {
	o.SetApplication(application)
	return o
}

// SetApplication adds the application to the put applications ID params
func (o *PutApplicationsIDParams) SetApplication(application *models.Application) {
	o.Application = application
}

// WithID adds the id to the put applications ID params
func (o *PutApplicationsIDParams) WithID(id string) *PutApplicationsIDParams {
	o.SetID(id)
	return o
}

// SetID adds the id to the put applications ID params
func (o *PutApplicationsIDParams) SetID(id string) {
	o.ID = id
}

// WriteToRequest writes these params to a swagger request
func (o *PutApplicationsIDParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if o.Application != nil {
		if err := r.SetBodyParam(o.Application); err != nil {
			return err
		}
	}

	// path param id
	if err := r.SetPathParam("id", o.ID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
