// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	"github.com/fogatlas/client-go/models"
)

// PutRelationshipsIDReader is a Reader for the PutRelationshipsID structure.
type PutRelationshipsIDReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *PutRelationshipsIDReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 201:
		result := NewPutRelationshipsIDCreated()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	case 400:
		result := NewPutRelationshipsIDBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	case 500:
		result := NewPutRelationshipsIDInternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewPutRelationshipsIDCreated creates a PutRelationshipsIDCreated with default headers values
func NewPutRelationshipsIDCreated() *PutRelationshipsIDCreated {
	return &PutRelationshipsIDCreated{}
}

/*PutRelationshipsIDCreated handles this case with default header values.

Created
*/
type PutRelationshipsIDCreated struct {
}

func (o *PutRelationshipsIDCreated) Error() string {
	return fmt.Sprintf("[PUT /relationships/{id}][%d] putRelationshipsIdCreated ", 201)
}

func (o *PutRelationshipsIDCreated) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewPutRelationshipsIDBadRequest creates a PutRelationshipsIDBadRequest with default headers values
func NewPutRelationshipsIDBadRequest() *PutRelationshipsIDBadRequest {
	return &PutRelationshipsIDBadRequest{}
}

/*PutRelationshipsIDBadRequest handles this case with default header values.

Invalid request
*/
type PutRelationshipsIDBadRequest struct {
	Payload *models.Message
}

func (o *PutRelationshipsIDBadRequest) Error() string {
	return fmt.Sprintf("[PUT /relationships/{id}][%d] putRelationshipsIdBadRequest  %+v", 400, o.Payload)
}

func (o *PutRelationshipsIDBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Message)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewPutRelationshipsIDInternalServerError creates a PutRelationshipsIDInternalServerError with default headers values
func NewPutRelationshipsIDInternalServerError() *PutRelationshipsIDInternalServerError {
	return &PutRelationshipsIDInternalServerError{}
}

/*PutRelationshipsIDInternalServerError handles this case with default header values.

Generic error
*/
type PutRelationshipsIDInternalServerError struct {
	Payload *models.Message
}

func (o *PutRelationshipsIDInternalServerError) Error() string {
	return fmt.Sprintf("[PUT /relationships/{id}][%d] putRelationshipsIdInternalServerError  %+v", 500, o.Payload)
}

func (o *PutRelationshipsIDInternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Message)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
