// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	"github.com/fogatlas/client-go/models"
)

// PutDataflowsIDReader is a Reader for the PutDataflowsID structure.
type PutDataflowsIDReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *PutDataflowsIDReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 201:
		result := NewPutDataflowsIDCreated()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	case 400:
		result := NewPutDataflowsIDBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	case 500:
		result := NewPutDataflowsIDInternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewPutDataflowsIDCreated creates a PutDataflowsIDCreated with default headers values
func NewPutDataflowsIDCreated() *PutDataflowsIDCreated {
	return &PutDataflowsIDCreated{}
}

/*PutDataflowsIDCreated handles this case with default header values.

Created
*/
type PutDataflowsIDCreated struct {
}

func (o *PutDataflowsIDCreated) Error() string {
	return fmt.Sprintf("[PUT /dataflows/{id}][%d] putDataflowsIdCreated ", 201)
}

func (o *PutDataflowsIDCreated) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewPutDataflowsIDBadRequest creates a PutDataflowsIDBadRequest with default headers values
func NewPutDataflowsIDBadRequest() *PutDataflowsIDBadRequest {
	return &PutDataflowsIDBadRequest{}
}

/*PutDataflowsIDBadRequest handles this case with default header values.

Invalid request
*/
type PutDataflowsIDBadRequest struct {
	Payload *models.Message
}

func (o *PutDataflowsIDBadRequest) Error() string {
	return fmt.Sprintf("[PUT /dataflows/{id}][%d] putDataflowsIdBadRequest  %+v", 400, o.Payload)
}

func (o *PutDataflowsIDBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Message)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewPutDataflowsIDInternalServerError creates a PutDataflowsIDInternalServerError with default headers values
func NewPutDataflowsIDInternalServerError() *PutDataflowsIDInternalServerError {
	return &PutDataflowsIDInternalServerError{}
}

/*PutDataflowsIDInternalServerError handles this case with default header values.

Generic error
*/
type PutDataflowsIDInternalServerError struct {
	Payload *models.Message
}

func (o *PutDataflowsIDInternalServerError) Error() string {
	return fmt.Sprintf("[PUT /dataflows/{id}][%d] putDataflowsIdInternalServerError  %+v", 500, o.Payload)
}

func (o *PutDataflowsIDInternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Message)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
