// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"
	"time"

	"golang.org/x/net/context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"

	"github.com/fogatlas/client-go/models"
)

// NewPutMicroservicesIDParams creates a new PutMicroservicesIDParams object
// with the default values initialized.
func NewPutMicroservicesIDParams() *PutMicroservicesIDParams {
	var ()
	return &PutMicroservicesIDParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewPutMicroservicesIDParamsWithTimeout creates a new PutMicroservicesIDParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewPutMicroservicesIDParamsWithTimeout(timeout time.Duration) *PutMicroservicesIDParams {
	var ()
	return &PutMicroservicesIDParams{

		timeout: timeout,
	}
}

// NewPutMicroservicesIDParamsWithContext creates a new PutMicroservicesIDParams object
// with the default values initialized, and the ability to set a context for a request
func NewPutMicroservicesIDParamsWithContext(ctx context.Context) *PutMicroservicesIDParams {
	var ()
	return &PutMicroservicesIDParams{

		Context: ctx,
	}
}

// NewPutMicroservicesIDParamsWithHTTPClient creates a new PutMicroservicesIDParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewPutMicroservicesIDParamsWithHTTPClient(client *http.Client) *PutMicroservicesIDParams {
	var ()
	return &PutMicroservicesIDParams{
		HTTPClient: client,
	}
}

/*PutMicroservicesIDParams contains all the parameters to send to the API endpoint
for the put microservices ID operation typically these are written to a http.Request
*/
type PutMicroservicesIDParams struct {

	/*ID*/
	ID string
	/*Microservice*/
	Microservice *models.Microservice

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the put microservices ID params
func (o *PutMicroservicesIDParams) WithTimeout(timeout time.Duration) *PutMicroservicesIDParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the put microservices ID params
func (o *PutMicroservicesIDParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the put microservices ID params
func (o *PutMicroservicesIDParams) WithContext(ctx context.Context) *PutMicroservicesIDParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the put microservices ID params
func (o *PutMicroservicesIDParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the put microservices ID params
func (o *PutMicroservicesIDParams) WithHTTPClient(client *http.Client) *PutMicroservicesIDParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the put microservices ID params
func (o *PutMicroservicesIDParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithID adds the id to the put microservices ID params
func (o *PutMicroservicesIDParams) WithID(id string) *PutMicroservicesIDParams {
	o.SetID(id)
	return o
}

// SetID adds the id to the put microservices ID params
func (o *PutMicroservicesIDParams) SetID(id string) {
	o.ID = id
}

// WithMicroservice adds the microservice to the put microservices ID params
func (o *PutMicroservicesIDParams) WithMicroservice(microservice *models.Microservice) *PutMicroservicesIDParams {
	o.SetMicroservice(microservice)
	return o
}

// SetMicroservice adds the microservice to the put microservices ID params
func (o *PutMicroservicesIDParams) SetMicroservice(microservice *models.Microservice) {
	o.Microservice = microservice
}

// WriteToRequest writes these params to a swagger request
func (o *PutMicroservicesIDParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param id
	if err := r.SetPathParam("id", o.ID); err != nil {
		return err
	}

	if o.Microservice != nil {
		if err := r.SetBodyParam(o.Microservice); err != nil {
			return err
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
