// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"
	"time"

	"golang.org/x/net/context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"

	"github.com/fogatlas/client-go/models"
)

// NewPutRegionsIDParams creates a new PutRegionsIDParams object
// with the default values initialized.
func NewPutRegionsIDParams() *PutRegionsIDParams {
	var ()
	return &PutRegionsIDParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewPutRegionsIDParamsWithTimeout creates a new PutRegionsIDParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewPutRegionsIDParamsWithTimeout(timeout time.Duration) *PutRegionsIDParams {
	var ()
	return &PutRegionsIDParams{

		timeout: timeout,
	}
}

// NewPutRegionsIDParamsWithContext creates a new PutRegionsIDParams object
// with the default values initialized, and the ability to set a context for a request
func NewPutRegionsIDParamsWithContext(ctx context.Context) *PutRegionsIDParams {
	var ()
	return &PutRegionsIDParams{

		Context: ctx,
	}
}

// NewPutRegionsIDParamsWithHTTPClient creates a new PutRegionsIDParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewPutRegionsIDParamsWithHTTPClient(client *http.Client) *PutRegionsIDParams {
	var ()
	return &PutRegionsIDParams{
		HTTPClient: client,
	}
}

/*PutRegionsIDParams contains all the parameters to send to the API endpoint
for the put regions ID operation typically these are written to a http.Request
*/
type PutRegionsIDParams struct {

	/*ID*/
	ID string
	/*Region*/
	Region *models.Region

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the put regions ID params
func (o *PutRegionsIDParams) WithTimeout(timeout time.Duration) *PutRegionsIDParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the put regions ID params
func (o *PutRegionsIDParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the put regions ID params
func (o *PutRegionsIDParams) WithContext(ctx context.Context) *PutRegionsIDParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the put regions ID params
func (o *PutRegionsIDParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the put regions ID params
func (o *PutRegionsIDParams) WithHTTPClient(client *http.Client) *PutRegionsIDParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the put regions ID params
func (o *PutRegionsIDParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithID adds the id to the put regions ID params
func (o *PutRegionsIDParams) WithID(id string) *PutRegionsIDParams {
	o.SetID(id)
	return o
}

// SetID adds the id to the put regions ID params
func (o *PutRegionsIDParams) SetID(id string) {
	o.ID = id
}

// WithRegion adds the region to the put regions ID params
func (o *PutRegionsIDParams) WithRegion(region *models.Region) *PutRegionsIDParams {
	o.SetRegion(region)
	return o
}

// SetRegion adds the region to the put regions ID params
func (o *PutRegionsIDParams) SetRegion(region *models.Region) {
	o.Region = region
}

// WriteToRequest writes these params to a swagger request
func (o *PutRegionsIDParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param id
	if err := r.SetPathParam("id", o.ID); err != nil {
		return err
	}

	if o.Region != nil {
		if err := r.SetBodyParam(o.Region); err != nil {
			return err
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
