// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	"github.com/fogatlas/client-go/models"
)

// PutDeploymentsNameReader is a Reader for the PutDeploymentsName structure.
type PutDeploymentsNameReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *PutDeploymentsNameReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 201:
		result := NewPutDeploymentsNameCreated()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	case 400:
		result := NewPutDeploymentsNameBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	case 500:
		result := NewPutDeploymentsNameInternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewPutDeploymentsNameCreated creates a PutDeploymentsNameCreated with default headers values
func NewPutDeploymentsNameCreated() *PutDeploymentsNameCreated {
	return &PutDeploymentsNameCreated{}
}

/*PutDeploymentsNameCreated handles this case with default header values.

Created
*/
type PutDeploymentsNameCreated struct {
}

func (o *PutDeploymentsNameCreated) Error() string {
	return fmt.Sprintf("[PUT /deployments/{name}][%d] putDeploymentsNameCreated ", 201)
}

func (o *PutDeploymentsNameCreated) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewPutDeploymentsNameBadRequest creates a PutDeploymentsNameBadRequest with default headers values
func NewPutDeploymentsNameBadRequest() *PutDeploymentsNameBadRequest {
	return &PutDeploymentsNameBadRequest{}
}

/*PutDeploymentsNameBadRequest handles this case with default header values.

Invalid request
*/
type PutDeploymentsNameBadRequest struct {
	Payload *models.Message
}

func (o *PutDeploymentsNameBadRequest) Error() string {
	return fmt.Sprintf("[PUT /deployments/{name}][%d] putDeploymentsNameBadRequest  %+v", 400, o.Payload)
}

func (o *PutDeploymentsNameBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Message)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewPutDeploymentsNameInternalServerError creates a PutDeploymentsNameInternalServerError with default headers values
func NewPutDeploymentsNameInternalServerError() *PutDeploymentsNameInternalServerError {
	return &PutDeploymentsNameInternalServerError{}
}

/*PutDeploymentsNameInternalServerError handles this case with default header values.

Generic error
*/
type PutDeploymentsNameInternalServerError struct {
	Payload *models.Message
}

func (o *PutDeploymentsNameInternalServerError) Error() string {
	return fmt.Sprintf("[PUT /deployments/{name}][%d] putDeploymentsNameInternalServerError  %+v", 500, o.Payload)
}

func (o *PutDeploymentsNameInternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Message)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
