// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"
	"time"

	"golang.org/x/net/context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"

	"github.com/fogatlas/client-go/models"
)

// NewPutDataflowsIDParams creates a new PutDataflowsIDParams object
// with the default values initialized.
func NewPutDataflowsIDParams() *PutDataflowsIDParams {
	var ()
	return &PutDataflowsIDParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewPutDataflowsIDParamsWithTimeout creates a new PutDataflowsIDParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewPutDataflowsIDParamsWithTimeout(timeout time.Duration) *PutDataflowsIDParams {
	var ()
	return &PutDataflowsIDParams{

		timeout: timeout,
	}
}

// NewPutDataflowsIDParamsWithContext creates a new PutDataflowsIDParams object
// with the default values initialized, and the ability to set a context for a request
func NewPutDataflowsIDParamsWithContext(ctx context.Context) *PutDataflowsIDParams {
	var ()
	return &PutDataflowsIDParams{

		Context: ctx,
	}
}

// NewPutDataflowsIDParamsWithHTTPClient creates a new PutDataflowsIDParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewPutDataflowsIDParamsWithHTTPClient(client *http.Client) *PutDataflowsIDParams {
	var ()
	return &PutDataflowsIDParams{
		HTTPClient: client,
	}
}

/*PutDataflowsIDParams contains all the parameters to send to the API endpoint
for the put dataflows ID operation typically these are written to a http.Request
*/
type PutDataflowsIDParams struct {

	/*Dataflow*/
	Dataflow *models.Dataflow
	/*ID*/
	ID string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the put dataflows ID params
func (o *PutDataflowsIDParams) WithTimeout(timeout time.Duration) *PutDataflowsIDParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the put dataflows ID params
func (o *PutDataflowsIDParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the put dataflows ID params
func (o *PutDataflowsIDParams) WithContext(ctx context.Context) *PutDataflowsIDParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the put dataflows ID params
func (o *PutDataflowsIDParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the put dataflows ID params
func (o *PutDataflowsIDParams) WithHTTPClient(client *http.Client) *PutDataflowsIDParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the put dataflows ID params
func (o *PutDataflowsIDParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithDataflow adds the dataflow to the put dataflows ID params
func (o *PutDataflowsIDParams) WithDataflow(dataflow *models.Dataflow) *PutDataflowsIDParams {
	o.SetDataflow(dataflow)
	return o
}

// SetDataflow adds the dataflow to the put dataflows ID params
func (o *PutDataflowsIDParams) SetDataflow(dataflow *models.Dataflow) {
	o.Dataflow = dataflow
}

// WithID adds the id to the put dataflows ID params
func (o *PutDataflowsIDParams) WithID(id string) *PutDataflowsIDParams {
	o.SetID(id)
	return o
}

// SetID adds the id to the put dataflows ID params
func (o *PutDataflowsIDParams) SetID(id string) {
	o.ID = id
}

// WriteToRequest writes these params to a swagger request
func (o *PutDataflowsIDParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if o.Dataflow != nil {
		if err := r.SetBodyParam(o.Dataflow); err != nil {
			return err
		}
	}

	// path param id
	if err := r.SetPathParam("id", o.ID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
