// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	"github.com/fogatlas/client-go/models"
)

// PutThingsIDReader is a Reader for the PutThingsID structure.
type PutThingsIDReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *PutThingsIDReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 201:
		result := NewPutThingsIDCreated()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	case 400:
		result := NewPutThingsIDBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	case 500:
		result := NewPutThingsIDInternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewPutThingsIDCreated creates a PutThingsIDCreated with default headers values
func NewPutThingsIDCreated() *PutThingsIDCreated {
	return &PutThingsIDCreated{}
}

/*PutThingsIDCreated handles this case with default header values.

Created
*/
type PutThingsIDCreated struct {
}

func (o *PutThingsIDCreated) Error() string {
	return fmt.Sprintf("[PUT /things/{id}][%d] putThingsIdCreated ", 201)
}

func (o *PutThingsIDCreated) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewPutThingsIDBadRequest creates a PutThingsIDBadRequest with default headers values
func NewPutThingsIDBadRequest() *PutThingsIDBadRequest {
	return &PutThingsIDBadRequest{}
}

/*PutThingsIDBadRequest handles this case with default header values.

Invalid request
*/
type PutThingsIDBadRequest struct {
	Payload *models.Message
}

func (o *PutThingsIDBadRequest) Error() string {
	return fmt.Sprintf("[PUT /things/{id}][%d] putThingsIdBadRequest  %+v", 400, o.Payload)
}

func (o *PutThingsIDBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Message)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewPutThingsIDInternalServerError creates a PutThingsIDInternalServerError with default headers values
func NewPutThingsIDInternalServerError() *PutThingsIDInternalServerError {
	return &PutThingsIDInternalServerError{}
}

/*PutThingsIDInternalServerError handles this case with default header values.

Generic error
*/
type PutThingsIDInternalServerError struct {
	Payload *models.Message
}

func (o *PutThingsIDInternalServerError) Error() string {
	return fmt.Sprintf("[PUT /things/{id}][%d] putThingsIdInternalServerError  %+v", 500, o.Payload)
}

func (o *PutThingsIDInternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Message)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
