// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	"github.com/fogatlas/client-go/models"
)

// PutRegionsIDReader is a Reader for the PutRegionsID structure.
type PutRegionsIDReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *PutRegionsIDReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 201:
		result := NewPutRegionsIDCreated()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	case 400:
		result := NewPutRegionsIDBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	case 500:
		result := NewPutRegionsIDInternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewPutRegionsIDCreated creates a PutRegionsIDCreated with default headers values
func NewPutRegionsIDCreated() *PutRegionsIDCreated {
	return &PutRegionsIDCreated{}
}

/*PutRegionsIDCreated handles this case with default header values.

Created
*/
type PutRegionsIDCreated struct {
}

func (o *PutRegionsIDCreated) Error() string {
	return fmt.Sprintf("[PUT /regions/{id}][%d] putRegionsIdCreated ", 201)
}

func (o *PutRegionsIDCreated) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewPutRegionsIDBadRequest creates a PutRegionsIDBadRequest with default headers values
func NewPutRegionsIDBadRequest() *PutRegionsIDBadRequest {
	return &PutRegionsIDBadRequest{}
}

/*PutRegionsIDBadRequest handles this case with default header values.

Invalid request
*/
type PutRegionsIDBadRequest struct {
	Payload *models.Message
}

func (o *PutRegionsIDBadRequest) Error() string {
	return fmt.Sprintf("[PUT /regions/{id}][%d] putRegionsIdBadRequest  %+v", 400, o.Payload)
}

func (o *PutRegionsIDBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Message)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewPutRegionsIDInternalServerError creates a PutRegionsIDInternalServerError with default headers values
func NewPutRegionsIDInternalServerError() *PutRegionsIDInternalServerError {
	return &PutRegionsIDInternalServerError{}
}

/*PutRegionsIDInternalServerError handles this case with default header values.

Generic error
*/
type PutRegionsIDInternalServerError struct {
	Payload *models.Message
}

func (o *PutRegionsIDInternalServerError) Error() string {
	return fmt.Sprintf("[PUT /regions/{id}][%d] putRegionsIdInternalServerError  %+v", 500, o.Payload)
}

func (o *PutRegionsIDInternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Message)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
