// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	"github.com/fogatlas/client-go/models"
)

// PutExternalendpointsIDReader is a Reader for the PutExternalendpointsID structure.
type PutExternalendpointsIDReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *PutExternalendpointsIDReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 201:
		result := NewPutExternalendpointsIDCreated()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	case 400:
		result := NewPutExternalendpointsIDBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	case 500:
		result := NewPutExternalendpointsIDInternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewPutExternalendpointsIDCreated creates a PutExternalendpointsIDCreated with default headers values
func NewPutExternalendpointsIDCreated() *PutExternalendpointsIDCreated {
	return &PutExternalendpointsIDCreated{}
}

/*PutExternalendpointsIDCreated handles this case with default header values.

Created
*/
type PutExternalendpointsIDCreated struct {
}

func (o *PutExternalendpointsIDCreated) Error() string {
	return fmt.Sprintf("[PUT /externalendpoints/{id}][%d] putExternalendpointsIdCreated ", 201)
}

func (o *PutExternalendpointsIDCreated) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewPutExternalendpointsIDBadRequest creates a PutExternalendpointsIDBadRequest with default headers values
func NewPutExternalendpointsIDBadRequest() *PutExternalendpointsIDBadRequest {
	return &PutExternalendpointsIDBadRequest{}
}

/*PutExternalendpointsIDBadRequest handles this case with default header values.

Invalid request
*/
type PutExternalendpointsIDBadRequest struct {
	Payload *models.Message
}

func (o *PutExternalendpointsIDBadRequest) Error() string {
	return fmt.Sprintf("[PUT /externalendpoints/{id}][%d] putExternalendpointsIdBadRequest  %+v", 400, o.Payload)
}

func (o *PutExternalendpointsIDBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Message)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewPutExternalendpointsIDInternalServerError creates a PutExternalendpointsIDInternalServerError with default headers values
func NewPutExternalendpointsIDInternalServerError() *PutExternalendpointsIDInternalServerError {
	return &PutExternalendpointsIDInternalServerError{}
}

/*PutExternalendpointsIDInternalServerError handles this case with default header values.

Generic error
*/
type PutExternalendpointsIDInternalServerError struct {
	Payload *models.Message
}

func (o *PutExternalendpointsIDInternalServerError) Error() string {
	return fmt.Sprintf("[PUT /externalendpoints/{id}][%d] putExternalendpointsIdInternalServerError  %+v", 500, o.Payload)
}

func (o *PutExternalendpointsIDInternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Message)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
