// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"
	"time"

	"golang.org/x/net/context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"

	"github.com/fogatlas/client-go/models"
)

// NewPutRelationshipsIDParams creates a new PutRelationshipsIDParams object
// with the default values initialized.
func NewPutRelationshipsIDParams() *PutRelationshipsIDParams {
	var ()
	return &PutRelationshipsIDParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewPutRelationshipsIDParamsWithTimeout creates a new PutRelationshipsIDParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewPutRelationshipsIDParamsWithTimeout(timeout time.Duration) *PutRelationshipsIDParams {
	var ()
	return &PutRelationshipsIDParams{

		timeout: timeout,
	}
}

// NewPutRelationshipsIDParamsWithContext creates a new PutRelationshipsIDParams object
// with the default values initialized, and the ability to set a context for a request
func NewPutRelationshipsIDParamsWithContext(ctx context.Context) *PutRelationshipsIDParams {
	var ()
	return &PutRelationshipsIDParams{

		Context: ctx,
	}
}

// NewPutRelationshipsIDParamsWithHTTPClient creates a new PutRelationshipsIDParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewPutRelationshipsIDParamsWithHTTPClient(client *http.Client) *PutRelationshipsIDParams {
	var ()
	return &PutRelationshipsIDParams{
		HTTPClient: client,
	}
}

/*PutRelationshipsIDParams contains all the parameters to send to the API endpoint
for the put relationships ID operation typically these are written to a http.Request
*/
type PutRelationshipsIDParams struct {

	/*ID*/
	ID string
	/*Relationship*/
	Relationship *models.Relationship

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the put relationships ID params
func (o *PutRelationshipsIDParams) WithTimeout(timeout time.Duration) *PutRelationshipsIDParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the put relationships ID params
func (o *PutRelationshipsIDParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the put relationships ID params
func (o *PutRelationshipsIDParams) WithContext(ctx context.Context) *PutRelationshipsIDParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the put relationships ID params
func (o *PutRelationshipsIDParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the put relationships ID params
func (o *PutRelationshipsIDParams) WithHTTPClient(client *http.Client) *PutRelationshipsIDParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the put relationships ID params
func (o *PutRelationshipsIDParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithID adds the id to the put relationships ID params
func (o *PutRelationshipsIDParams) WithID(id string) *PutRelationshipsIDParams {
	o.SetID(id)
	return o
}

// SetID adds the id to the put relationships ID params
func (o *PutRelationshipsIDParams) SetID(id string) {
	o.ID = id
}

// WithRelationship adds the relationship to the put relationships ID params
func (o *PutRelationshipsIDParams) WithRelationship(relationship *models.Relationship) *PutRelationshipsIDParams {
	o.SetRelationship(relationship)
	return o
}

// SetRelationship adds the relationship to the put relationships ID params
func (o *PutRelationshipsIDParams) SetRelationship(relationship *models.Relationship) {
	o.Relationship = relationship
}

// WriteToRequest writes these params to a swagger request
func (o *PutRelationshipsIDParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param id
	if err := r.SetPathParam("id", o.ID); err != nil {
		return err
	}

	if o.Relationship != nil {
		if err := r.SetBodyParam(o.Relationship); err != nil {
			return err
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
