// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/swag"
)

// ApplicationMicroservicesItems application microservices items
// swagger:model applicationMicroservicesItems
type ApplicationMicroservicesItems struct {

	// microservice id
	MicroserviceID string `json:"microservice_id,omitempty"`
}

// Validate validates this application microservices items
func (m *ApplicationMicroservicesItems) Validate(formats strfmt.Registry) error {
	var res []error

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

// MarshalBinary interface implementation
func (m *ApplicationMicroservicesItems) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *ApplicationMicroservicesItems) UnmarshalBinary(b []byte) error {
	var res ApplicationMicroservicesItems
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
