// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/swag"
)

// DynamicNode Represent a bare metal node that can be commissioned (join the cluster) and decommissioned
// swagger:model DynamicNode
type DynamicNode struct {

	// id
	ID string `json:"id,omitempty"`

	// ip address
	IPAddress string `json:"ip_address,omitempty"`

	// Id of the corresponding node in the cluster
	NodeID string `json:"node_id,omitempty"`

	// region id
	RegionID string `json:"region_id,omitempty"`
}

// Validate validates this dynamic node
func (m *DynamicNode) Validate(formats strfmt.Registry) error {
	var res []error

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

// MarshalBinary interface implementation
func (m *DynamicNode) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *DynamicNode) UnmarshalBinary(b []byte) error {
	var res DynamicNode
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
