// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/swag"
)

// GetDeploymentsOKBody get deployments o k body
// swagger:model getDeploymentsOKBody
type GetDeploymentsOKBody struct {

	// deployments
	Deployments GetDeploymentsOKBodyDeployments `json:"deployments"`
}

// Validate validates this get deployments o k body
func (m *GetDeploymentsOKBody) Validate(formats strfmt.Registry) error {
	var res []error

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

// MarshalBinary interface implementation
func (m *GetDeploymentsOKBody) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *GetDeploymentsOKBody) UnmarshalBinary(b []byte) error {
	var res GetDeploymentsOKBody
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
