// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/swag"
)

// GetDataflowsOKBody get dataflows o k body
// swagger:model getDataflowsOKBody
type GetDataflowsOKBody struct {

	// dataflows
	Dataflows GetDataflowsOKBodyDataflows `json:"dataflows"`
}

// Validate validates this get dataflows o k body
func (m *GetDataflowsOKBody) Validate(formats strfmt.Registry) error {
	var res []error

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

// MarshalBinary interface implementation
func (m *GetDataflowsOKBody) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *GetDataflowsOKBody) UnmarshalBinary(b []byte) error {
	var res GetDataflowsOKBody
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
