// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/swag"
)

// GetMicroservicesOKBody get microservices o k body
// swagger:model getMicroservicesOKBody
type GetMicroservicesOKBody struct {

	// microservices
	Microservices GetMicroservicesOKBodyMicroservices `json:"microservices"`
}

// Validate validates this get microservices o k body
func (m *GetMicroservicesOKBody) Validate(formats strfmt.Registry) error {
	var res []error

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

// MarshalBinary interface implementation
func (m *GetMicroservicesOKBody) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *GetMicroservicesOKBody) UnmarshalBinary(b []byte) error {
	var res GetMicroservicesOKBody
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
