// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/swag"
)

// Microservice microservice
// swagger:model Microservice
type Microservice struct {

	// application id
	ApplicationID string `json:"application_id,omitempty"`

	// description
	Description string `json:"description,omitempty"`

	// Unique id retrieved by the monitor from the underlying PaaS system (k8s)
	ID string `json:"id,omitempty"`

	// Unique FogAtlas internal name, defined by the user in a deployment request
	Name string `json:"name,omitempty"`

	// node id
	NodeID string `json:"node_id,omitempty"`

	// region id
	RegionID string `json:"region_id,omitempty"`

	// status
	Status string `json:"status,omitempty"`
}

// Validate validates this microservice
func (m *Microservice) Validate(formats strfmt.Registry) error {
	var res []error

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

// MarshalBinary interface implementation
func (m *Microservice) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *Microservice) UnmarshalBinary(b []byte) error {
	var res Microservice
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
