// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/swag"
)

// RegionRelationshipsItems region relationships items
// swagger:model regionRelationshipsItems
type RegionRelationshipsItems struct {

	// relationship id
	RelationshipID string `json:"relationship_id,omitempty"`
}

// Validate validates this region relationships items
func (m *RegionRelationshipsItems) Validate(formats strfmt.Registry) error {
	var res []error

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

// MarshalBinary interface implementation
func (m *RegionRelationshipsItems) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *RegionRelationshipsItems) UnmarshalBinary(b []byte) error {
	var res RegionRelationshipsItems
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
